### DISCUSSION TITLE
Unable to view files using onlyoffice

### DISCUSSION THREAD

**Discussion by colin715** [gtsteffaniak/filebrowser#331] [General]
I have added onlyoffice per the instructions, have generated the JWT secret, have set up external access via NPM, and can enter in my external domain in the browser and am able to see the welcome screen.  But I keep getting the "Preview not available for this file" message when I try to open an xls or ods file.

docker-compose:
```
services:
  filebrowser:
    image: gtstef/filebrowser
    ports:
      - 446:80
    volumes:
      - /homepool:/srv
      - ./database:/home/filebrowser/database
      - ./config.yaml:/home/filebrowser/config.yaml
    restart: always
  onlyoffice:
    image: onlyoffice/documentserver
    environment:
      JWT_SECRET: MY_SECRET
    ports:
      - 8089:80
```

config:
```
server:
  internalUrl: "http://192.168.1.25/"
  port: 80
  baseURL: "/"
  database: "/database/database.db"
  sources:
    - name: "Documents"
      path: "/srv/Documents"
integrations:
  office:
    url: "https://editor.mydomain.com"
    secret: MY_SECRET
```
