### DISCUSSION TITLE
Issue downloading office documents?

### DISCUSSION THREAD

**Discussion by JusticeGH** [gtsteffaniak/filebrowser#486] [Q&A]
I am experiencing a strange issue when trying to download office related documents (i.e. .xlsx, docx, etc.)

When trying to download a file from mobile, it correctly displays the filename and extension:
![Screenshot_20250404_010401_Samsung Internet](https://github.com/user-attachments/assets/ee873728-952c-47cb-bc29-9b462fde31b2)

However, when the file is downloaded, it compresses it into a zip with the following contents:
![Screenshot_20250404_010445_My Files](https://github.com/user-attachments/assets/9483e690-fd91-44e9-a9c9-c9f180c771bb)

I don't recall having this issue before, but perhaps I never tried to download a file like this onto my mobile before.

Any help is greatly appreciated :)

**Comment by JusticeGH** [comment]
If you need any additional information, I'm happy to help where I can.

**Comment by JusticeGH** [comment]
Some additional information if you find it helpful:
To eliminate a variable, I accessed the File Browser server directly with <ip>:<port> instead of going through my internal RP, Traefik.

Still got the same result so it's unlikely to be caused by any Traefik header configuration.

I'm guessing the MIME type isn't set correctly within File Browser itself?


Let me know if you want me to check anything else.

**Comment by gtsteffaniak** [comment]
Hey sorry I didn't see this , I don't check discussions as frequently. (for future reference, post in issues. I can't track discussions the same.)

I can't replicate this, but I think there could be two things going on:

1. perhaps the browser is doing something weird I might be able to account for. Does this same issue happen for chome/safari etc?
2. like you mentioned, perhaps something with the mimetype (but I don't think download cares the mimetype). Could you check the right click > info ? It should say something like ` application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` for xlsx

**Reply by JusticeGH** [reply]
> Hey sorry I didn't see this , I don't check discussions as frequently. (for future reference, post in issues. I can't track discussions the same.)
> 
> I can't replicate this, but I think there could be two things going on:
> 
>     1. perhaps the browser is doing something weird I might be able to account for. Does this same issue happen for chome/safari etc?
> 
>     2. like you mentioned, perhaps something with the mimetype (but I don't think download cares the mimetype). Could you check the right click > info ? It should say something like ` application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` for xlsx

All good - was just trying to keep stuff organized and wasn't sure if it was actually a bug.

This is happening on my mobile using Samsung Internet. I just downloaded and tried it with Firefox: Focus and instead of downloading as `....xlsx.zip`, it's just replacing the `.xlsx` extension completely with `.zip`.

Here is what the `info` says:
![Screenshot_20250410_192710_Samsung Internet](https://github.com/user-attachments/assets/58d64345-27eb-442d-aa83-40a42aa78269)

Let me know if you'd like me to try anything else.

**Reply by gtsteffaniak** [reply]
Assuming you have a reverse proxy here? Probably messing with the response. Can you give me details on any proxy or app hosting service you have?

**Reply by JusticeGH** [reply]
> Assuming you have a reverse proxy here? Probably messing with the response. Can you give me details on any proxy or app hosting service you have?

Yes, I am using Traefik.

Here is the Traefik compose.yml file:
```
networks:
  frontend:
    external: true

services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs/:/var/traefik/certs/:rw
    restart: unless-stopped
    networks:
      - frontend
    security_opt:
      - "no-new-privileges=true"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker.exposedbydefault=false"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"

      # Setup LetsEncrypt certificate resolver
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=ariadne.ns.cloudflare.com,shane.ns.cloudflare.com"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.propagation.delayBeforeChecks=20"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.propagation.disableChecks=true"
      - "--certificatesresolvers.letsencrypt.acme.keyType=EC384"
      - "--certificatesresolvers.letsencrypt.acme.email=[EMAIL_REDACTED]"
      - "--certificatesresolvers.letsencrypt.acme.storage=/var/traefik/certs/acme.json"

      # Staging environment for LetsEncrypt, comment out below for real certs
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

      # Setup insecure listener that redirects all traffic to TLS
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.http.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.https.address=:443"

      # Setup the TLS configuration for our secure https listener
      - "--entrypoints.https.http.tls=true"
      - "--entrypoints.https.http.tls.certResolver=letsencrypt"
      - "--entrypoints.https.http.tls.domains[0].main=justinhome.vip"
      - "--entrypoints.https.http.tls.domains[0].sans=*.justinhome.vip"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.justinhome.vip`)"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
```

File Browser's compose.yml:
```
networks:
  frontend:
    external: true
  filebrowser_bridge:
    driver: bridge

services:
  filebrowser:
    image: gtstef/filebrowser:0.6.6-beta
    container_name: filebrowser
    restart: unless-stopped
    user: filebrowser  # Run as a non-root user
    ports:
      - "8081:80"  # Map container port 80 to host port 8081
    volumes:
      - /mnt/c/Users/Justin:/srv  # Required, maps the base directory to /srv
      - /mnt/d:/srv/d:ro # Map additional drives
      - ./database:/home/filebrowser/database  # Persistent storage for database
      - ./config.yaml:/home/filebrowser/config.yaml  # Mount the configuration file
    security_opt:
      - "no-new-privileges:true"  # Prevent privilege escalation
    read_only: false  # Set the container's filesystem to read-only
    tmpfs:
      - /tmp  # Mount a temporary filesystem for /tmp
    cap_drop:
      - ALL  # Drop all Linux capabilities
    networks:
      - frontend
      - filebrowser_bridge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.filebrowser-https.tls=true"
      - "traefik.http.routers.filebrowser-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filebrowser-https.entrypoints=https"
      - "traefik.http.routers.filebrowser-https.rule=Host(`files.justinhome.vip`)"
      - "traefik.http.routers.filebrowser-https.service=filebrowser"
      - "traefik.http.routers.filebrowser-catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.filebrowser-catchall.entrypoints=http"
      - "traefik.http.routers.filebrowser-catchall.service=filebrowser"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
```

and finally File Brower's config.yml:
```
server:
  port: 80
  sources:
    - name: "C: Drive"
      path: "/srv"
    - name: "D: Drive"
      path: "/srv/d"

auth:
  adminUsername: [USERNAME_REDACTED]
  adminPassword: [PASSWORD_REDACTED]
  signup: false
  methods:
    noauth: false
    password:
      enabled: true
      minLength: 10

userDefaults:
  locale: "en"
  viewMode: "list"
  singleClick: true
  permissions:
    create: true
    rename: true
    modify: true
    delete: true
    share: true
    download: true
    admin: true
    execute: false
    api: false
  hideDotfiles: true
  darkMode: true
  settingsAllowed: true

frontend:
  name: "FileBrowser"
  disableDefaultLinks: false
  externalLinks:
    - text: "Home"
      url: "https://files.justinhome.vip"
```

**Reply by gtsteffaniak** [reply]
So I looked over everything and to be honest the proxy looks right. I don't see any reason for the issue you are seeing.

The biggest clue I think is the fact the download sometimes shows as `.zip`, this tells me its something wrong with filebrowser. There is logic that checks if something is a directory or single file. I went over it again and there was a situation an error with symbolic link could be incorrectly seen as a directory which would trigger a zip creation. I tweaked this so its more reliable in v0.6.8, however I don't think thats the issue.

Also, I noticed you're running v0.6.6, and there were several download related changes since then. Can you upgrade to v0.6.8 (make sure your config passes validation), and let me know if you still see the issue?

**Reply by JusticeGH** [reply]
> So I looked over everything and to be honest the proxy looks right. I don't see any reason for the issue you are seeing.
> 
> The biggest clue I think is the fact the download sometimes shows as `.zip`, this tells me its something wrong with filebrowser. There is logic that checks if something is a directory or single file. I went over it again and there was a situation an error with symbolic link could be incorrectly seen as a directory which would trigger a zip creation. I tweaked this so its more reliable in v0.6.8, however I don't think thats the issue.
> 
> Also, I noticed you're running v0.6.6, and there were several download related changes since then. Can you upgrade to v0.6.8 (make sure your config passes validation), and let me know if you still see the issue?

I have updated to 0.6.8-beta and changed my config.yml file to the following:
```
server:
  numImageProcessors: 4
  socket: ''
  tlsKey: ''
  tlsCert: ''
  enableThumbnails: true
  resizePreview: false
  port: 80
  baseURL: /
  logging:
    - levels: ''
      apiLevels: ''
      output: stdout
      noColors: false
      json: false
  database: database.db
  sources:
    - name: "C: Drive"
      path: "/srv"
      config:
        indexingInterval: 0
        disabled: false
        maxWatchers: 0
        neverWatchPaths: null
        ignoreHidden: false
        ignoreZeroSizeFolders: false
        exclude:
          files: null
          folders: null
          fileEndsWith: null
        include:
          files: null
          folders: null
          fileEndsWith: null
        defaultUserScope: ''
        defaultEnabled: true
        createUserDir: false
    - name: "D: Drive"
      path: "/srv/d"
      config:
        indexingInterval: 0
        disabled: false
        maxWatchers: 0
        neverWatchPaths: null
        ignoreHidden: false
        ignoreZeroSizeFolders: false
        exclude:
          files: null
          folders: null
          fileEndsWith: null
        include:
          files: null
          folders: null
          fileEndsWith: null
        defaultUserScope: ''
        defaultEnabled: true
        createUserDir: false
  externalUrl: ''
  internalUrl: ''
  cacheDir: tmp
  maxArchiveSize: 50

auth:
  tokenExpirationHours: 2
  methods:
    proxy:
      enabled: false
      createUser: false
      header: ''
    noauth: false
    password:
      enabled: true
      minLength: 10
      signup: false
      recaptcha:
        host: ''
        key: ''
        secret: ''
  key: ''
  adminUsername: USERNAME_REDACTED
  adminPassword: PASSWORD_REDACTED

frontend:
  name: "FileBrowser"
  disableDefaultLinks: false
  disableUsedPercentage: false
  externalLinks:
    - text: "Home"
      title: ""
      url: "https://files.justinhome.vip"

userDefaults:
  stickySidebar: true
  darkMode: true
  lockPassword: false
  locale: "en"
  viewMode: "list"
  gallerySize: 3
  singleClick: true
  permissions:
    api: false
    admin: true
    modify: true
    share: true
  showHidden: false
  dateFormat: false
  themeColor: "var(--blue)"
  quickDownload: false
  disableOnlyOfficeExt: ".txt .csv .html .pdf"

integrations:
  office:
    url: ''
    secret: ''
```

Tried download a .xlsx file on both Samsung Internet and Firefox Focus and now I'm seeing slightly different results.

Samsung Internet still downloads as .xlsx.zip where Firefox Focus completely supplants the .xlsx extension with only .zip.
