### DISCUSSION TITLE
How to get Sign Ups working?

### DISCUSSION THREAD

**Discussion by MrRobotjs** [gtsteffaniak/filebrowser#558] [Q&A]
I'm using Docker and I'm pretty sure to have configured everything correctly but when I try to sign up as a regular user I get a "Wrong credentials" error and in the console it is a 405 error. But I'm able to create users from my admin dashboard and login in to that user.

docker-compose
```
filebrowser-quantum:
    image: gtstef/filebrowser:0.6.8-beta
    container_name: filebrowser-quantum
    ports:
      - '8084:80'
    volumes:
      - "G:/Media+:/home/filebrowser/Media+"
      # optional if you want db to persist - configure a path under "database" dir in config file.
      - ./filebrowser-quantum/database:/home/filebrowser/database
      - ./filebrowser-quantum/config.yaml:/home/filebrowser/config.yaml
      # optional mount a temp directory to use. Generally, there is no need for this unless your user is not root or filebrowser.
      # - './tmp/:/home/filebrowser/tmp/'
    # optionally run as non-root filebrowser user
    #user: filebrowser
    restart: always
```
config
```
server:
  numImageProcessors: 4
  socket: ''
  tlsKey: ''
  tlsCert: ''
  enableThumbnails: true
  resizePreview: false
  port: 80
  baseURL: /
  logging:
    - levels: ''
      apiLevels: ''
      output: stdout
      noColors: false
      json: false
  database: database.db
  sources:
    - path: "/home/filebrowser/Media+"
      name: Media
      config:
        indexingInterval: 0
        disabled: false
        maxWatchers: 0
        neverWatchPaths: null
        ignoreHidden: false
        ignoreZeroSizeFolders: false
        exclude:
          files: null
          folders: null
          fileEndsWith: null
        include:
          files: null
          folders: null
          fileEndsWith: null
        defaultUserScope: ''
        defaultEnabled: true
        createUserDir: false
  externalUrl: ''
  internalUrl: ''
  cacheDir: tmp
  maxArchiveSize: 50
auth:
  tokenExpirationHours: 2
  methods:
    proxy:
      enabled: false
      createUser: false
      header: ''
    noauth: false
    password:
      enabled: true
      minLength: 5
      signup: true
      recaptcha:
        host: ''
        key: ''
        secret: ''
  key: ''
  adminUsername: redacted
  adminPassword: redacted
frontend:
  name: FileBrowser Quantum
  disableDefaultLinks: false
  disableUsedPercentage: false
  externalLinks:
    - text: Discord
      title: Arr Sanctuary
      url: 'redacted'
userDefaults:
  stickySidebar: true
  darkMode: true
  lockPassword: false
  locale: en
  viewMode: normal
  gallerySize: 3
  singleClick: false
  permissions:
    api: false
    admin: false
    modify: false
    share: true
  showHidden: false
  dateFormat: false
  themeColor: var(--blue)
  quickDownload: true
  disableOnlyOfficeExt: .csv .html .pdf
integrations:
  office:
    url: ''
    secret: ''
```

https://github.com/user-attachments/assets/94b12b89-0d5c-4df4-b8dc-e7938186254b
