### DISCUSSION TITLE
Issue when browsing mounted folders

### DISCUSSION THREAD

**Discussion by bearded-papa** [gtsteffaniak/filebrowser#771] [Q&A]
I have set up with the compose and config below but keep getting the following error when browsing folders
error: 
```
Error: {"status":500,"message":"could not stat path: /media/media/backups, lstat /media/media/backups: no such file or directory"}
```
compose.yml
```
services:
  filebrowser:
    image: gtstef/filebrowser
    container_name: filebrowser_quantum
    volumes:
      - /mnt/media:/media
      - /mnt/archive:/archive
      - /:/root
      # optional if you want db to persist - configure a path under "database" dir in config file.
      - /mnt/media/docker/appdata/filebrowser_quantum/database:/home/filebrowser/database
      - /mnt/media/docker/appdata/filebrowser_quantum/config.yaml:/home/filebrowser/config.yaml
      # optional mount a temp directory to use. Generally, there is no need for this unless your user is not root or filebrowser.
      # - './tmp/:/home/filebrowser/tmp/'
    ports:
      - 8825:80
    # Optionally run as non-root filebrowser user
    #user: filebrowser
    restart: unless-stopped
```
config.yml
```
server:
  port: 80
  database: "/home/filebrowser/database/database" # placing in the database directory so it shows up on the host with>
  sources:
    - path: /media # corresponds to the folder mounted above in docker-compose
      name: Media
   #  - path: /archive
     #  name: Archive
   #  - path: /root
     #  name: Root
```
