### ISSUE TITLE
Can’t use it with IPad 

### ISSUE THREAD

**Issue by pbranly** [gtsteffaniak/filebrowser#251]
hi
I mainly share my installation with my iPad
I have installed her docker.
It works fine but I don’t have the equivalent of « right click » so I can’t do anything 
Is there a solution ?
Thanks 
Phil

**Comment by gtsteffaniak** [comment]
I have not tested on an iPad but I don't see any reason it wouldn't work.

It should be a **press and hold** to initiate right click -- just confirming have you tried that?

if not, let me know and I will see if I can replicate

**Comment by pbranly** [comment]
Hi
For sure I tried 
Either it does not react, or it opens an iPad window 
But it does not open the filebrowser one.
Don’t hesitate to ask me any help
Phil
Ps: I verified that it works on my windows PC. Therefore this is really IPad linked 
![IMG_4233](https://github.com/user-attachments/assets/6d1e12f9-e1e1-4cb7-9d8b-adafe932b1cb)

**Comment by pbranly** [comment]
Hi
I made new tests from my windows computer
I can create a directory but the file transfert does not work
There is not any message and nothing is changed 
Phil

**Comment by pbranly** [comment]
Hi 
Any news about that ?
thanks
Phil

**Comment by gtsteffaniak** [comment]
I have an idea what it might be, but I don't have an iPad to test. I'll have more time this weekend to make a change and see if that fixes it this weekend. I'll let you know

**Comment by pbranly** [comment]
Hi,
Thank you
I have understood the second critical issue from my windows computer this time:
files are created as root even if i run the docker under UID/GID 1000
So filebrowser cannot do anything
this is my config:

```
  filebrowser_quantum:
    container_name: filebrowser_quantum
    volumes:
      - /media/xxxxxx:/srv # required (for now not configurable)
      - ./filebrowser_quantum/database:/database  # optional if you want db to persist - configure a path under "database" dir in config file.
      - ./filebrowser_quantum/config/filebrowser.yaml:/filebrowser.yaml
    ports:
      - '9444:80'
    image: gtstef/filebrowser
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Paris
```
regards
Phil

**Comment by gtsteffaniak** [comment]
setting environment variables in docker does not "run as" that user, but right now non root users are not supported.

I am about to release v0.3.3 which should fix this and (hopefully) the right-click issue on iPad.

You config would look like this on v0.3.3:


```
  filebrowser_quantum:
    container_name: filebrowser_quantum
    volumes:
      - /media/xxxxxx:/srv # required (for now not configurable)
      - ./filebrowser_quantum/database:/filebrowser/home/database  # optional if you want db to persist - configure a path under "database" dir in config file.
      - ./filebrowser_quantum/config/filebrowser.yaml:/home/filebrowser/config.yaml
    ports:
      - '9444:80'
    image: gtstef/filebrowser
    restart: always
    user: filebrowser
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Paris
```

**Comment by pbranly** [comment]
Fantastic thank you
My mistake was exact !
The addition of the user line generates the following error with the current version
Error response from daemon: unable to find user filebrowser: no matching entries in passwd file
is it normal ? 
will it work with the upcoming version ?
Phil

**Comment by gtsteffaniak** [comment]
yes thats expected , because linux does not see user "1000" and the version to support this user will be released here in a minute... you'll need to update your config to match the above so it points to `/home/filebrowser/config.yaml`

And make sure you get the latest image by doing `docker pull gtstef/filebrowser` to pull the new latest image (once its released)

**Comment by pbranly** [comment]
It does not start 
I have this error:
panic: mkdir /database: permission denied

latest not yet available but I use dev_v0.3.3

**Comment by gtsteffaniak** [comment]
yeah -- you'll need to update the paths, I provided the correct paths in [this comment](https://github.com/gtsteffaniak/filebrowser/issues/251#issuecomment-2546054762) 

I also have the readme updated 
<img width="851" alt="image" src="https://github.com/user-attachments/assets/23e4dba9-f1d6-458b-a4ca-5daacd9eabbf" />

**Comment by pbranly** [comment]
Ok
I had to remove the old database that had been created as root 
And had to empty the existing config file 
And it started 
But long press on my IPad does not do anything now 
Phil

**Comment by pbranly** [comment]
There is a mismatch 
    - ./filebrowser_quantum/config/filebrowser.yaml:/home/filebrowser/config.yaml
    it should be I think
    - ./filebrowser_quantum/config/filebrowser.yaml:/filebrowser/home/config.yaml

**Comment by pbranly** [comment]
It does not work with the modification
2024-12-16T17:38:43.608831081Z 2024/12/16 17:38:43 open config.yaml: no such file or directory
2024-12-16T17:38:45.450588785Z 2024/12/16 17:38:45 open config.yaml: no such file or directory
2024-12-16T17:38:48.882120511Z 2024/12/16 17:38:48 open config.yaml: no such file or directory
2024-12-16T17:38:55.530991019Z 2024/12/16 17:38:55 open config.yaml: no such file or directory
and with yours, the file was not updated 

I will rework everything from the PC as soon as available 
Not easy from iPad ! 
please clarify the exact conf file if necessary
Phil

**Comment by gtsteffaniak** [comment]
Ah yeah I think I may have typed it backwards, this should work:

```
services:
  filebrowser:
    volumes:
      - /media/xxxxxx:/srv
      - ./filebrowser_quantum/database:/home/filebrowser/database
      - ./filebrowser_quantum/config/filebrowser.yaml:/home/filebrowser/config.yaml
    ports:
      - '9444:80'
    image: gtstef/filebrowser:dev_v0.3.3
    restart: unless-stopped
```

**Comment by pbranly** [comment]
No
Whatever modification I do, there is not any database file generated
The long press still gives iPad menu but not your menu
I will work on the PC to morrow
Thanks
Phil

**Comment by gtsteffaniak** [comment]
youll also need to update your config file database path:

from something like :
```
server:
  port: 9444
  database: "/database/filebrowser.db"
  baseURL: "/"
```

To:
```
server:
  port: 9444
  database: "database/filebrowser.db"
  baseURL: "/"
```

Good catch, ill update the readme to mention this as well

**Comment by gtsteffaniak** [comment]
and I just tested in safari and I do see a long press issue in safari, let me see if I can fix that.

I bet it would work in another browser, but its good I am able to replicate the issue... so I should be able to fix.

**Comment by pbranly** [comment]
> youll also need to update your config file database path:
> 
> from something like :
> 
> ```
> server:
>   port: 80
>   database: "/database/filebrowser.db"
>   baseURL: "/"
> ```
> 
> To:
> 
> ```
> server:
>   port: 80
>   database: "database/filebrowser.db"
>   baseURL: "/"
> ```
> 
> Good catch, ill update the readme to mention this as well

Heu
I don’t see any difference between both configurations ( from
 …. To … seem the same)

edit:I found  the difference !
But port should stay 80 as it is your side isnt it ?

**Comment by pbranly** [comment]
> and I just tested in safari and I do see a long press issue in safari, let me see if I can fix that.
> 
> I bet it would work in another browser, but its good I am able to replicate the issue... so I should be able to fix.

Fine

**Comment by gtsteffaniak** [comment]
yeah no port changes should be needed, so should be:

```
server:
  port: 80
  database: "database/filebrowser.db"
  baseURL: "/"
```

Can you `docker pull gtstef/filebrowser:dev_v0.3.3` again and test on your iPad? I think I fixed the right-click menu for safari.
