### ISSUE TITLE
Unable to use proxy auth with Authentik and Traefik 3

### ISSUE THREAD

**Issue by joshoram80** [gtsteffaniak/filebrowser#322]
**Description**

Using proxy header auth with Authentik + Traefik shows login screen and prevents login by any user, including admin

**Expected behaviour**

User is logged into Filebrowser when logged into Authentik using X-authentik-username header

**What is happening instead?**

`GET     | 401 | 192.168.90.254:33052 |              | 71.79µs      | "/api/users?id=self"` is the only error

**How to reproduce?**

config.yaml
```
auth:
  method: proxy
  header: "X-authentik-username"
```
Traefik middleware
```
http:
  middlewares:
    middlewares-authentik:
      forwardAuth:
        address: "http://authentik_server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```
and Filebrowser behind Authentik forwardAuth middleware.
I am presented with the login screen, even though the user exists in Filebrowser, and the header is parsed (I doubled checked and setup Traefik's whoami container which shows all the headers passed. It's setup using the exact same middleware as FB)
