### ISSUE TITLE
create new files under a custom uid/gid

### ISSUE THREAD

**Issue by Scud0** [gtsteffaniak/filebrowser#328]
i use shared storage for multiple containers.
filebrowser creates new files under root:root. 

it would be helpfull if i can set (environment variable?) a custom uid:gid that filebrowser uses for new files. 

i tried running the the filebrowser container with `user: {uid}:{gid}` but then the container wont start, no permission to create database.db.

**Comment by gtsteffaniak** [comment]
Check out running the container with non root user on the [configuration wiki](https://github.com/gtsteffaniak/filebrowser/wiki/Configuration)

You can specify the username "filebrowser" in docker compose or in `docker run -u filebrowser`

That should solve your issue

**Comment by gtsteffaniak** [comment]
```
services:
  filebrowser:
    volumes:
      - '/path/to/folder:/srv' # required (for now not configurable)
      # optional if you want db to persist - configure a path under "database" dir in config file.
      - 'database:/home/filebrowser/database'
      - 'config.yaml:/home/filebrowser/config.yaml'
    ports:
      - '80:80'
    image: gtstef/filebrowser
    user: filebrowser
    restart: unless-stopped
```
