### ISSUE TITLE
Serving filebrowser via proxy under a path called /files/ causes file list to not load

### ISSUE THREAD

**Issue by 29821632** [gtsteffaniak/filebrowser#362]
**Description**
Proxying filebrowser behind nginx under a URL with a trailing path of `/files/` such as `http://foo.example.org/files/` with matching `baseURL: "/files/"` causes the file list to hang on "Loading..." and not load the initial files/folders into view.
Changing the trailing directory in the proxy configuration and `baseURL` to something other than the string "files", for example "foo", and it works perfectly.

**Expected behaviour**
File list to load regardless of the name used for the sub-path

**What is happening instead?**
Browser address bar redirects to http://foo.example.org/files/files/ and hangs on "Loading..."
![Image](https://github.com/user-attachments/assets/e534b70d-83f4-4f50-b0e2-240ec366595d)

**Additional context**
Initially suspected it was a redirect loop caused by my nginx config but checking browser dev tools and nginx logs doesn't show any failed requests or redirect loops. All HTTP 200 responses from filebrowser, hitting the correct static resources and API endpoint paths such as `GET /files/api/resources?path=%2F&content=false HTTP/1.1\r\n`.
Ran tcpdump to capture the HTTP between the proxy and the filebrowser docker container and the API requests and responses all return 200 OK.

The JSON response of the file listing API request to `/files/api/resources?path=%2F&content=false` appears valid and identical regardless of the directory/`baseURL` setting.
For example:
```
{"name":"srv","size":0,"modified":"2025-02-10T18:10:13.970902972Z","type":"directory","hidden":false,"files":[{"name":"HELLO.md","size":0,"modified":"2025-02-10T18:07:30.193234299Z","type":"text/markdown","hidden":false},{"name":"HELLO1.md","size":0,"modified":"2025-02-10T18:09:41.621560971Z","type":"text/markdown","hidden":false},{"name":"HELLO2.md","size":0,"modified":"2025-02-10T18:09:43.274527353Z","type":"text/markdown","hidden":false},{"name":"HELLO3.md","size":0,"modified":"2025-02-10T18:09:47.843434419Z","type":"text/markdown","hidden":false}],"folders":[],"path":"/","source":""}
```

**How to reproduce?**
Running via docker-compose:
```
services:
  filebrowser:
    image: gtstef/filebrowser
    restart: always
    ports:
      - '8082:80'
    volumes:
      - '/storage/myfiles:/srv' # required (for now not configurable)
      # optional if you want db to persist - configure a path under "database" dir in config file.
      - './database:/home/filebrowser/database'
      - './config.yaml:/home/filebrowser/config.yaml'
      - './cache:/cache'
```

`config.yaml`
```
server:
  port: 80
  baseURL: "/files/"
  cacheDir: "/cache"
  externalUrl: "https://foo.example.org/"
  database: "/database/database.db"
  sources:
    - name: "default"
      path: "/srv"
  numImageProcessors: 4
  enableThumbnails: true
  resizePreview: true
  typeDetectionByHeader: true
  logging:
    - output: stdout
      levels: "info|warning|error|debug"
      apiLevels: "info|warning|error"
auth:
  signup: false
  methods:
    noauth: true
frontend:
  name: "foo"
userDefaults:
  showHidden: true
  singleClick: true
```

nginx proxy configuration...
Part of a wider virtual host so only showing the filebrowser-specific config
```
...
    location ~ ^/files/.* {
        client_max_body_size 10G;

        proxy_pass http://127.0.0.1:8082;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header X-Username "proxy-user";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
...
```

**Files**
Configuration as above.
