### ISSUE TITLE
auth proxy with non existing users failing even when createUser true

### ISSUE THREAD

**Issue by alexanderccc** [gtsteffaniak/filebrowser#375]
**Description**
Configuring auth proxy with `createUser: true` returns a 500 error when logging in.

auth configuration is set as follows:

```yaml
auth:
  signup: false
  methods:
    noauth: false
    password:
      enabled: false
    proxy:
      enabled: true
      header: "X-authentik-name"
      createUser: true
```

During the page load, there is this request

```
GET https://files.<domain>/api/users?id=self
{
	"status": 500,
	"message": "password must be at least 5 characters long"
}
```

**Expected behaviour**
There shouldn't be any password required on the filebrowser side.

**Additional context**
This isn't that important to me right away, just mentioning it for awareness. 
I use filebrowser as an admin tool, I could even do without user management 🤷‍
Currently keeping it as `noauth: true` and dealing with the authentication at the proxy level

Project works well otherwise, appreciate the work!

**Comment by gtsteffaniak** [comment]
I did add min length password config after I fixed the proxy header. I think there's an issue where it's still looking for a min length.

Even though password is set to false, could you try adding "minLength: 0" to password config and see if that works as a workaround for now?

```
  methods:
    password:
      enabled: false
      minLength: 0
```

I'll have a proper fix in the next release.
