### ISSUE TITLE
File Download Caches Entire Contents In Memory

### ISSUE THREAD

**Issue by generallund** [gtsteffaniak/filebrowser#412]
This isn't necessarily a bug, but something I wanted to make you aware of incase you weren't already. 

It appears as though when someone is downloading a file, it loads the entirety of that file into memory. I had a user download a 30gb file, and saw the memory in my server jump by 30gb until the download was completed. I checked memory usage in procmon and it was indeed filebrowser that was using that large amount of memory (just wanted to make sure it wasn't some weird cache setting I had on my end).

Like I said, I don't suppose this is a glaring issue, but I'd be curious to see how it reacts/what happens if I had multiple people pulling multiple of these large files (or even a handful pulling smaller files) whose total size exceeded the memory available in the server.

Thanks again for the amazing work you're doing here!

**Comment by gtsteffaniak** [comment]
Hmm interesting, sounds like a bug to me. It could be that the transfer isn't sent with chunk encoding, ill test and confirm this gets fixed. Thanks for opening this

**Comment by gtsteffaniak** [comment]
I tested this, it doesn't "Caches Entire Contents In Memory".

For example when downloading a 5GB file, I see RAM increase by 30-50 MB, which could be due to streaming logic.

It could be that there are multiple simultaneous downloads happening at once, or some other leak somewhere else, but I don't think its an issue with the downloaded file being stored in memory.

I have added some enhancement related to this in 0.6.1, including some debug logging for large file downloads (when larger than 100MB), but I would like you to provide feedback after v0.6.1 goes live.

**Comment by generallund** [comment]
Will gladly do so :)

**Comment by Scud0** [comment]
v061-beta and a 5GB file download increases mem usage by 4MB (as reported by docker stats)

**Comment by generallund** [comment]
No memory spikes after upgrading to 6.1 :)

I am however now encountering an error when trying to download from the search bar, I receive this type of error no matter what I try to download:

`Looks like there’s a problem with this site`
`https://URL.com/api/raw?files=D:\::/LocalTVShows//LocalTVShows/1899/1899 - Season 1/1899 S01E04.mkv&algo=tar.gz might have a temporary problem or it could have moved.`
`Error code: 500 Internal Server Error`

and in the console log

`2025/03/12 13:15:12 GET     | 500 | 192.168.1.1:57541 | admin        | 1ms          | "/api/raw?files=D%3A%5C%3A%3A%2FLocalTVShows%2F%2FLocalTVShows%2F1899%2F1899%20-%20Season%201%2F1899%20S01E04.mkv&algo=tar.gz"`

I can/will open another issue for this if you'd like :)

**Comment by gtsteffaniak** [comment]
no worries its releated to downloads, lets leave it on this thread. another good check i can add to the tests! this is very likely because of the source change that happened.

now its in this format `files=<source>::<path>`

looking at your path something looks wrong:

source: `D:\`
path: `/LocalTVShows//LocalTVShows/1899/1899 - Season 1/1899 S01E04.mkv&algo=tar.gz`

seems like `LocalTVShows` is there twice, ill check if I can reproduce this.

**Comment by generallund** [comment]
Yes I had to reconfigure the config.yaml file when I moved to 6.0, as mentioned in the release notes. I had a bit of trouble getting it to like what I put in there, but ultimately this worked:
`  sources:`
`    - path: "D:"`

For further clarification: Downloads work from within the UI if I go to the file directly. It's only when using the search bar I receive the error posted above.

**Comment by gtsteffaniak** [comment]
I'll take a look , something like "D:\" should work, I'll test this on windows and make sure it works for next bugfix focused release early next week.

**Comment by generallund** [comment]
> I'll take a look , something like "D:" should work, I'll test this on windows and make sure it works for next bugfix focused release early next week.

I have updated to 0.6.2 and it appears to be working fine now! I don't know if this was actually an issue on my end somehow... I updated to 0.6.2 and tested it to confirm it was working, then rolled back to 0.6.1 and it was working again as well on the older version... No changes to the config.yaml inbetween reporting this issue and now though so not sure what was up there!

**Comment by gtsteffaniak** [comment]
Interesting, I didn't test this issue yet so thank you for doing that.

I don't know what happened, but for now let's close. You can open a new issue of something happens with that again.

**Comment by gtsteffaniak** [comment]
FYI, I did find a bug related to windows on this, I bet you added names to your sources in your config? Anyways, a fix is coming in v0.6.3 for anyone else in the future.

**Comment by generallund** [comment]
Hm I don't think so? config.yaml is below:

```
server:
  indexing: true
  tlsKey: "key.pem"
  tlsCert: "cert.pem"
  enableThumbnails: true
  port: <redacted>
  numImageProcessors: 4
  baseURL: ""
  database: database.db
  log: stdout
  sources:
    - path: "D:"
auth:
  adminUsername: <redacted>
  adminPassword: <redacted>
  methods:
    noauth: false
    password:
      enabled: true
      minLength: 12
  signup: false
frontend:
  name: "<redacted>"
  disableUsedPercentage: true
userDefaults:
  settingsAllowed: true
  darkMode: true
  locale: "en"
  permissions:
    admin: false
    modify: false
    share: false
    api: false
```
