### ISSUE TITLE
bug: 403 (Forbidden) for admin

### ISSUE THREAD

**Issue by baur** [gtsteffaniak/filebrowser#439]
**Description**

I see 403 (Forbidden) on view (PDF) or download, but files listed and available

```yaml
  sources:
    - name: "SRC1"
      path: "E:/app"
    - name: "SRC2"
      path: "E:/distr"  
```

![Image](https://github.com/user-attachments/assets/657adcf6-dc87-4b72-a309-85349f6ac993)

![Image](https://github.com/user-attachments/assets/5a554707-31bc-43a2-9b1a-e9991349873f)
