### ISSUE TITLE
CreateUserDir not working

### ISSUE THREAD

**Issue by ojmaster** [gtsteffaniak/filebrowser#440]
Hello, i am trying out filebrowser quantum before I move over but I am having one big issue currently, when a new user is created it does not auto provision them a new directory with scopes to that folder only. I am using proxy auth and have `createUser: true` so I expected it to create the new user directory and scope it to that. my config
The file set up I am going for is: /srv/users/{username}, just like how the original fileBrowser is. I want new users to have a folder provisioned to them under users and their scope to be only seeing that folder.
```
server:
  CreateUserDir: true
  externalUrl: "https://files.example.com"
  internalUrl: "http://10.0.0.61:9829"
  sources:
    - name: "default"
      path: "/srv"
      config:
        defaultUserScope: "/users"
        defaultEnabled: true
auth:
  signup: false
  methods:
    noauth: false
    password:
      enabled: true
      minLength: 7  # set min password length requirement -- defaults to 5 if unset
    proxy:
      enabled: true
      header: "X-fileBrowser-User"  # header which should container username
      createUser: true      # automatically creates user with default user properties
userDefaults:
  darkMode: true
frontend:
  name: "Files"
```
