### ISSUE TITLE
Download on shares doesn't work

### ISSUE THREAD

**Issue by bunkerman** [gtsteffaniak/filebrowser#465]
**Description**
External downloads don't work

**Expected behaviour**
download via sharing should wokr

**What is happening instead?**
{"status":400,"message":"invalid file in files request: "}
{"status":500,"message":"error fetching share from server"}

**Additional context**
The shared folder is visible, also outside of LAN, but download gives the 400/500 error messages

docker compose
```
version: "3.8"
services:
  filebrowser:
    volumes:
      - /nas:/srv
      - /share/filebrowser-quantum/database:/home/filebrowser/database
      - /share/filebrowser-quantum/config.yaml:/home/filebrowser/config.yaml
    ports:
      - 49688:80
    image: gtstef/filebrowser
    user: 1000:100
    restart: unless-stopped
```

config.yaml
```
frontend:
  name: "Kays Filebrowser"
  disableDefaultLinks: true
  externalLinks:
    - text: "Kays Filebrowser"
      url: "https://files.example.com"
      title: "Sharing is Caring"
auth:
  signup: false
  methods:
    noauth: false
#    password:
#      enabled: true
#      minLength: 7  # set min password length requirement -- defaults to 5 if unset
#    proxy:
#      enabled: true
#      header: "proxy-user"  # header which should container username
#      createUser: true      # automatically creates user with default user properties
server:
  internalUrl: "http://ip:49688/"
  externalUrl: "https://files.example.com/"
  port: 80
  baseURL: "/"
  database: "/home/filebrowser/database/database.db"
  sources:
    - name: "kknas"
      path: "/srv"
integrations:
  office:
    url: "https://office.example.com"
    secret: xyz
```

The database.db file was copied from the og filebrowser

**Comment by maxlivi** [comment]
Same here, it seems that the latest working version is 0.54.

**Comment by gtsteffaniak** [comment]
I if I understand correctly, external download links meaning this affects the links that should be created with the external url?

https://files.example.com/

Should be an easy fix, but I'll also need to add an integration test to make sure this doesn't break again in the future.

**Comment by bunkerman** [comment]
Thanks. The link is created correctly via the share  button like https://files.example.com/share/rJ4rtBo9vRQhMWhMrErL2w
but I can't download the content from the folder. The content of the folder is displayed correctly.
The sharing is working correctly on the og filebrowser.

I also should add, that I use authelia and excluding the url with api and share to make sharing work.

**Comment by gtsteffaniak** [comment]
should be fixed in 0.6.5, can you confirm?

**Comment by bunkerman** [comment]
works, thx

**Comment by Scud0** [comment]
v065, and it doesnt work. 

browser console:
`{"status":500,"message":"error fetching share from server"}`

container log:
```
`2025/04/02 13:24:51 [ERROR] error fetching file info for share tlbPH9A1TI9VLVkhb8ho_g / file/folder does not exist to refresh data: /Apps/someapp.apk

2025/04/02 13:24:51 GET     | 500 | 192.168.1.1:54722 |              | 0ms          | "/api/public/share?path=/&hash=tlbPH9A1TI9VLVkhb8ho_g"`
```

**Comment by bunkerman** [comment]
I did check again. Links work on LAN but not on WAN. maybe it's an authelia issue. I will check the logs.
@gtsteffaniak But are the sharing links different to the og filebrowser? Because I excluded them  from authelia.

**Comment by gtsteffaniak** [comment]
@Scud0 can you recreate the share and see if it still happens? If I recall correctly, I may have always made the share path "/", so if the existing share was created before it may not work...

And thinking about that I should have announced that.

**Comment by Scud0** [comment]
> [@Scud0](https://github.com/Scud0) can you recreate the share and see if it still happens? If I recall correctly, I may have always made the share path "/", so if the existing share was created before it may not work...
> 
> And thinking about that I should have announced that.

Share was created fresh today on v065. Also retried some different files to troubleshoot. All the same error. 

// File browser is behind a reverse proxy. Accessing it via fqdn.
I can try a direct connect on ip tomorrow.

**Comment by gtsteffaniak** [comment]
If you are using docker, can you try this dev version and let me know if it fixes it?

`gtstef/filebrowser:0.6.6-dev` 

I have tested this locally and this works with normal and externalUrl, would like feedback before releasing.

**Comment by Scud0** [comment]
> If you are using docker, can you try this dev version and let me know if it fixes it?
> 
> `gtstef/filebrowser:0.6.6-dev`
> 
> I have tested this locally and this works with normal and externalUrl, would like feedback before releasing.

doesnt solve this issue here. 

same error. both via fqdn as direct connect on ip.

**Comment by gtsteffaniak** [comment]
Do you guys happen to be using proxy auth? I noticed there is a bug with this, which will get addressed

**Comment by gtsteffaniak** [comment]
Since there a few comments on here and I am not sure whats left. I have a new v0.6.6 release which resolves some issues around proxy user config and externalUrl.

It may not resolve the issue, but please test and if you still encounter an issue, post your config and screenshots again in a new issue so I can be certain which issue I am fixing.

**Comment by bunkerman** [comment]
@gtsteffaniak @Scud0 I think I got it working with authelia.
I'm using authelia for authentication (also waiting for the filebrowser quantum OIDC implementation).
to make external sharing work with the og filebrowser I had to bypass:
```
- domain: files.example.com
      policy: bypass
      resources:
        - "^/api/public/dl/*"
        - "/share/*"
        - "/static/js/*"
        - "/static/css/*"
        - "/static/img/*"
        - "/static/themes/*"
        - "/static/fonts/*"
        - "/static/assets/*"
```

but filebrowser quantum additionally needs to bypass

`"^/api/public/*"`

Authentik users are also affected by this. It should get resolved with the OIDC implementation.

I have 2 questions:
- Do I need all those links bypassed?
- Do I need the proxy setting in the config and what does it do?
