### ISSUE TITLE
Share link return 500 error

### ISSUE THREAD

**Issue by christaikobo** [gtsteffaniak/filebrowser#478]
**Description**
I have generated a share link, and when visiting it in the incognito mode browser, I got an error:
![Image](https://github.com/user-attachments/assets/c59f1a39-8af8-498d-b944-ae67a142c7b5)
![Image](https://github.com/user-attachments/assets/0c9c8725-c886-45d3-9b8c-8859a893f079)
`{"status":500,"message":"error fetching share from server"}`

**Expected behaviour**
Share link works

**What is happening instead?**
Share link does not work, throws 500 error

**Comment by gtsteffaniak** [comment]
If you are using docker, can you try this dev version and let me know if it fixes it?

`gtstef/filebrowser:0.6.6-dev` 

I have tested this locally and this works with normal and externalUrl, would like feedback before releasing.

**Comment by christaikobo** [comment]
Sure thing happy to help. Testing right now.

**Comment by christaikobo** [comment]
Unfortunately it's still the same. FYI not using external URL right now. 

![Image](https://github.com/user-attachments/assets/29363a93-4caa-4055-8bed-8b12127e022a)

![Image](https://github.com/user-attachments/assets/dfc01cc4-1829-490a-81d7-96008eaaf43b)

![Image](https://github.com/user-attachments/assets/59e13eeb-b376-4a61-b599-ba5abe8901c0)

![Image](https://github.com/user-attachments/assets/e573990d-9161-490d-bf88-5988be78ae12)

**Comment by gtsteffaniak** [comment]
Thanks for testing , it's good you are using docker this makes it easy to test.

I bet it's something specific to the paths in your config. Could you post your config for me to try to replicate? ( And removing any private info )

**Comment by christaikobo** [comment]
Sure, here you are:

```
frontend:
  disableUsedPercentage: true

auth:
  signup: false
  methods:
    noauth: false
    password:
      enabled: false
      minLength: 16
    proxy:
      enabled: true
      header: "Remote-User"
      createUser: false

server:
  port: 7000
  baseURL: "/filebrowser"
  database: "/home/filebrowser/filebrowser.db"
  sources:
    - name: "Default"
      path: "/source"
      config:
        defaultUserScope: "/users"
        defaultEnabled: true
        createUserDir: true
  logging:
    - output: "/home/filebrowser/filebrowser.log"
      levels: "info"
```

```
docker run \
  -d --restart unless-stopped \
  --name filebrowser \
  --hostname filebrowser \
  --net isolate --ip ****** \
  -e TZ=America/******** \
  -u 1026:101 \
  -v /path1/filebrowser:/source \
  -v /path2/docker/filebrowser/config.yaml:/home/filebrowser/config.yaml \
  -v /path2/docker/filebrowser/filebrowser.db:/home/filebrowser/filebrowser.db \
  -v /path2/docker/filebrowser/filebrowser.log:/home/filebrowser/filebrowser.log \
  gtstef/filebrowser:0.6.6-dev
```
