### ISSUE TITLE
Is there a complete example of a configuration file ？

### ISSUE THREAD

**Issue by spysir** [gtsteffaniak/filebrowser#496]
I would like an example of a complete configuration file ？Thanks

**Comment by gtsteffaniak** [comment]
I know there needs to be a better way to view the full config, perhaps in settings somewhere. But the reason I don't provide one and usually point to the configuration wiki is because things change all the time... adding new options and features.

anyways, here's an example full config (you can see from going to /api/settings with an admin user logged in)

```
---
server:
  numImageProcessors: 4
  socket: 
  tlsKey: 
  tlsCert: 
  enableThumbnails: true
  resizePreview: false
  authHook: 
  port: 80
  baseURL: "/"
  logging:
  - levels: 
    apiLevels: 
    output: stdout
    noColors: false
    json: false
  database: database.db
  userHomeBasePath: 
  sources:
  - path: "/home/graham"
    name: drive
    config:
      indexingInterval: 0
      disabled: false
      maxWatchers: 0
      neverWatchPaths: 
      ignoreHidden: false
      ignoreZeroSizeFolders: false
      exclude:
        files: 
        folders: 
        fileEndsWith: 
      include:
        files: 
        folders: 
        fileEndsWith: 
      defaultUserScope: 
      defaultEnabled: true
      createUserDir: false
  externalUrl: 
  internalUrl: 
  cacheDir: tmp
  maxArchiveSize: 50
auth:
  tokenExpirationHours: 2
  recaptcha:
    host: 
    key: 
    secret: 
  methods:
    proxy:
      enabled: false
      createUser: false
      header: 
    noauth: false
    password:
      enabled: true
      minLength: 5
  signup: false
  adminUsername: admin
  adminPassword: admin
  AuthMethods:
  - Password
frontend:
  name: FileBrowser Quantum
  disableDefaultLinks: false
  disableUsedPercentage: false
userDefaults:
  stickySidebar: true
  darkMode: true
  lockPassword: false
  locale: en
  viewMode: normal
  gallerySize: 3
  singleClick: false
  permissions:
    api: false
    admin: false
    modify: false
    share: false
  showHidden: false
  dateFormat: false
  themeColor: var(--blue)
  quickDownload: false
  disableOnlyOfficeExt: ".txt .csv .html .pdf"
integrations:
  office:
    url: 
    secret:
```
