### ISSUE TITLE
Running docker using non root user causes permission issue

### ISSUE THREAD

**Issue by christaikobo** [gtsteffaniak/filebrowser#497]
**Description**
When running docker using `-u 1026:101`, I got `[FATAL] failed to create file cache: can't make directory tmp: mkdir tmp: permission denied`

**Expected behaviour**
Docker container starts.

**What is happening instead?**
Docker container cannot be started

**Additional context**
It used to work in 0.6.5

**Comment by gtsteffaniak** [comment]
A tmp dir was added , might need to update the docker file. Will double check

**Comment by gtsteffaniak** [comment]
I tested this with non-root setup which has user 1000 permissions, and it does work just fine still. The user for the docker container needs to be able to create directories in the `/home/filebrowser` path.

The docker container expects either root or user 1000 (filebrowser user). I am not sure why you need `1026`, but if you must use that user, I would recommend creating a tmp directory with those chmod user permissions and mounting it to the container:

```
services:
  filebrowser:
    volumes:
      - '/path/to/folder:/folder'
      - 'database.db:/home/filebrowser/database.db'
      - tmp:/home/filebrowser/tmp
      - 'config.yaml:/home/filebrowser/config.yaml'
    ports:
      - '80:80'
    image: gtstef/filebrowser
    user: filebrowser
    restart: unless-stopped
```
