### ISSUE TITLE
redirect url for searched file has an extra `/` in it.

### ISSUE THREAD

**Issue by Scud0** [gtsteffaniak/filebrowser#501]
v066. 

login
search a file
click on the found file and get an error 500

issue is most likely and incorrect url constructed from the found file's location. i.e.:  hover over the found file and look at the url it wants to open. it has a double `/`

**Comment by gtsteffaniak** [comment]
whats your config? What error message do you see in the popup or on your console?

can't replicate on my side and no related changes that I am aware of.

**Comment by Scud0** [comment]
popup: 
`
Error: {"status":500,"message":"could not stat path: /srv/%2FNextcloud%20Manual.pdf, lstat /srv/%2FNextcloud%20Manual.pdf: no such file or directory"} 
`


console: 


config:

```
server:
  CreateUserDir: false
  UserHomeBasePath: ""
  numImageProcessors: 4
  socket: ""
  tlsKey: ""
  tlsCert: ""
  enableThumbnails: false
  resizePreview: true
  typeDetectionByHeader: true
  port: 80
  baseURL: "/"
  database: "/database/database.db"
  sources:
    - name: "default"
      path: "/srv"
  externalUrl: ""
  internalUrl: ""
auth:
  adminUsername: XXXXXX
  adminPassword: XXXXXX
  recaptcha:
    host: ""
    key: ""
    secret: ""
  tokenExpirationHours: 2
  methods:
    noauth: false
    password:
      enabled: true
      minLength: 8
    proxy:
      enabled: false
      header: "my-proxy-user-header"
      createUser: true
  signup: false
frontend:
  name: "FileBrowser"
  disableDefaultLinks: false
  disableUsedPercentage: false
  externalLinks:
    - text: "Your custom link"
      url: "https://example.com"
      title: "this text appears when hovering over link"
  color: ""
userDefaults:
  settingsAllowed: true
  darkMode: false
  scope: ""
  locale: "en"
  viewMode: ""
  singleClick: true
  permissions:
    admin: true
    modify: true
    share: true
    api: true
  showHidden: false
  dateFormat: false
integrations:
  office:
    url: "https://XXXXXX"   # eg. a public internet IP/domain
    secret: "XXXXXX"      # same secret from above
```

**Comment by gtsteffaniak** [comment]
ok that looks like a url encode issue, the filename was double encoded, so it should only happen for files with spaces or special characters, let me see if there was a recent change to that.

**Comment by gtsteffaniak** [comment]
feel free to delete the photo, i think your URL is at the bottom.

I just tested this and again don't see an issue, but there may be a scenario this could happen -- ill just have to go over the code.

**Comment by Scud0** [comment]
> ok that looks like a url encode issue, the filename was double encoded, so it should only happen for files with spaces or special characters, let me see if there was a recent change to that.

I have this for every file, not only files with specials characters.

**Comment by gtsteffaniak** [comment]
what's the last version that works?

**Comment by Scud0** [comment]
still having the issue with 060. further back and it breaks on the config. 

did some additional testing: 
- dont have this issue when the full path + file has no spaces. 

![Image](https://github.com/user-attachments/assets/25c5d5a7-3686-4ff1-8d03-704294e9ed9a)

- do have issues when the file has spaces. double spaces encoding happens: 

![Image](https://github.com/user-attachments/assets/db9be561-0a96-45e2-a1d3-6a0eb69151c1)

- do have issues when the folder has spaces and file has no spaces:


![Image](https://github.com/user-attachments/assets/dd5ad397-a117-4d0c-8a91-9372126808f4)

**Comment by gtsteffaniak** [comment]
Ok yeah theres definitely related changes in v0.6.0.

That's very interesting, there's a bug somewhere I'll try to replicate using your config.

**Comment by gtsteffaniak** [comment]
I bet this happens when only one source exists.

Just as a test can you add another source like:

```
  sources:
    - name: "default"
      path: "/srv"
    - path: "."
```

I bet it won't be an issue... And the tests I have are mostly with multiple sources.
