### ISSUE TITLE
Auth for admin, but allow "anonymous" users

### ISSUE THREAD

**Issue by NullVsNone** [gtsteffaniak/filebrowser#505]
Not sure if this already exists based on config, but looking to set up a system such that there's an `admin`/`registered` user that requires you to log in. But then there's also "anonymous" usage such that you have access to the public folders.

---

Specifically, the ability to:

1. Allow anonymous users read-only access to designated "public" folders (e.g., `filebrowser.com/files/Public`).
2. Require users to log in (`filebrowser.com/login`) to access all other "private" folders (e.g., `filebrowser.com/files/Private`), based on their user permissions.

This would allow using a single instance for things like public downloads alongside private team files. Just wanted to share this thought in case it's a useful addition for others too.

```yaml
auth:
  signup: false
  adminUsername: "admin"
  adminPassword: "reallyStrongPassword"
  methods:
    noauth: true
    password:
      enabled: false
      minLength: 0
server:
  port: 80
  sources:
    - name: "Public"
      path: "/srv/Public"
    - name: "Private"
      path: "/srv/Private"
```

**Comment by gtsteffaniak** [comment]
Yeah this is a good enhancement. This could also flow nicely with this change that is planned https://github.com/gtsteffaniak/filebrowser/issues/473

Meaning, the structure could be for the example config you gave:

access public source;

-  `/public/files/Public/dir/path`
- `/public/api/resources?path=/dir/path&source=Public`

accessing private:

- `/files/Private/dir/path/`
- `/api/resources?path=/dir/path&source=Private`

And shares from either source would be:

- `/public/share/<hash>`

And potentially a config like:

```
  sources:
    - name: "Public"
      path: "/srv/Public"
      config:
        public: true
    - name: "Private"
      path: "/srv/Private"
```
