### ISSUE TITLE
Docker restart (or stop/start) resets the users' defined scopes

### ISSUE THREAD

**Issue by msd96** [gtsteffaniak/filebrowser#515]
Description
After every docker stop and docker start, all previously defined user scopes are reset. I have to manually reconfigure the scopes again and again, which is frustrating and affects productivity.

Expected behaviour
User scopes should persist across Docker restarts. Once configured, they should remain intact unless explicitly changed.

What is happening instead?
User scopes are cleared after stopping and starting the Docker container.
Each time the container is restarted, I have to manually set the scopes again.

Additional context
This may be related to volumes or data persistence in the container setup.
Please advise if there’s a recommended way to make scopes persistent.

How to reproduce?

Set user scopes.

Run docker stop <container>

Run docker start <container>

Observe that scopes are reset.

**Comment by gtsteffaniak** [comment]
That would be annoying, let me check why that might be happening. A simple fix would come in v0.6.8

**Comment by gtsteffaniak** [comment]
im not able to replicate this. Are you mounting your database ? does it show `Using existing database` on startup or creating a new database each time?

**Comment by msd96** [comment]
@gtsteffaniak , yes I'm mounting the database as mentioned in the installation instruction. And it shows `Using existing database` on startup. I'm using my old database from original filebrowser, it contains our users. One of my aims for shifting to Quantum FileBrowser was to have multiple scopes per user, it's really a helpful feature. I defined many sources in the `config.yaml` and mapped them to the users using the UI through admin account. The database persists when I add users, even after restartings. I expected to have this behavior (persistance) after mapping the scopes to the users, but unfortunately every time when stop/start the docker contianer, I lose those configuraitons.
I tried using `docker` and `docker compose`, both of them didn't work for me.
This is my `filebrowser-compose.yaml` file:
```
services:
  filebrowser:
    image: gtstef/filebrowser
    container_name: quantum-filebrowser
    ports:
      - "8080:443"
    volumes:
      - /somepath/cert.pem:/home/filebrowser/cert.pem
      - /somepath/privkey.pem:/home/filebrowser/privkey.pem
      - /somepath/database.db:/home/filebrowser/database.db
      - /somepath/config.yaml:/home/filebrowser/config.yaml
      - /home:/srv
    restart: unless-stopped
```
 
and this is my `config.yaml`:
```
server:
  port: 443
  baseURL:  "/"
  tlsCert: /home/filebrowser/cert.pem
  tlsKey: /home/filebrowser/privkey.pem
  logging:
    - levels: "info|debug|warning|error"
  sources:
    - name: "Share"
      path: "/srv"

    - name: "Audit"
      path: "/srv/audit"
    - name: "Audit - Accounting"
      path: "/srv/audit/Accounting"
    - name: "Audit - Customer Servicing"
      path: "/srv/audit/Customer Servicing"
    - name: "Audit - Financing"
      path: "/srv/audit/Financing"
    # ... more source pathes
    database: /home/filebrowser/filebrowser_new.db
auth:
  signup: false
userDefaults:
  darkMode: true
  disableSettings: false
  scope: "."
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
```

command to run:
`docker compose -f filebrowser-compose.yaml up -d`

logs:
```
2025/04/10 08:54:22 [INFO ] root.go:73: Initializing FileBrowser Quantum (testing)
2025/04/10 08:54:22 [INFO ] root.go:74: Using Config file        : config.yaml
2025/04/10 08:54:22 [INFO ] root.go:75: Auth Methods             : [Password]
2025/04/10 08:54:22 [INFO ] root.go:76: Using existing database  : /home/filebrowser/database.db
2025/04/10 08:54:22 [INFO ] root.go:77: Sources                  : [credit - shahritus: /srv/file_exchange/credit/shahritus compliance - bonki_markazi: /...
```

where am I wrong, please help 🙏
