### ISSUE TITLE
Wrong folder path gets displayed in filebrowser.

### ISSUE THREAD

**Issue by VonAdam1** [gtsteffaniak/filebrowser#519]
**Description**
I'm trying to run FileBrowser Quantum using Docker Compose, with the goal of accessing a specific mounted volume on my Mac. The path is not showing what i expect.

**Expected behaviour**
When I open FileBrowser, I expect to see the contents of /Volumes/_DELIVERIES/SHARABLES/ mounted correctly at /srv, as specified in my docker-compose.yml.

**What is happening instead?**
It shows my local files.
But whats weird is that, "http" and "tmp" are not files i can see. And the file "filebrowser" gets displayed as a file (see image) but it should displays as a folder.

<img width="2558" alt="Image" src="https://github.com/user-attachments/assets/aa10da28-4b41-4f47-be83-50326e0a4706" />

**Additional context**
File sharing in Docker resources.
<img width="731" alt="Image" src="https://github.com/user-attachments/assets/30d970f6-6b79-4c22-892c-bd008cdb01b5" />

**How to reproduce?**
1. Use attached files. 
2. Use same file sharing in Docker

**Files**
These 2 folders should be located in /User/yourname/
[reproduce.zip](https://github.com/user-attachments/files/19686134/reproduce.zip)

**Comment by gtsteffaniak** [comment]
I see the issue its with your config, its due to an indenting error... In upcoming 0.7.0 I am making a change to validate the config before running which should prevent typos like this.

```
server:
    port: 80
    address: ""
    database: /home/filebrowser/database/database.db
    sources:
    - name: "Test"
    path: /srv
```

`path` is being ignored here because its not part of the sources array. It should look like this:

```
server:
  port: 80
  address: ""
  database: /home/filebrowser/database/database.db
  sources:
    - name: "Test"
      path: /srv
```

The way you have it configured it defaults to the path of the current directory.
