### ISSUE TITLE
Config validation failed

### ISSUE THREAD

**Issue by christaikobo** [gtsteffaniak/filebrowser#527]
**Description**
```
auth:
  methods:
    noauth: false
    password:
      enabled: false
      minLength: 16
    proxy:
      enabled: true
      header: "Remote-User"
      createUser: false
```
I got `could not validate Key: 'Settings.Auth.Methods.PasswordAuth.Enabled' Error:Field validation for 'Enabled' failed on the 'required' tag`

I am confused, am I not allowed to use `enabled: false` for `password`?
