### ISSUE TITLE
Editing text files with in built editor is buggy

### ISSUE THREAD

**Issue by BaccanoMob** [gtsteffaniak/filebrowser#535]
**Description**

https://github.com/user-attachments/assets/d8012a16-0b77-4e7f-93c8-fbc0c02ab226

Above video explains better than my typing. New folder and new file works as intended. Notice that 0.0 bytes are created (and is reflected in local filesystem) but could not be edited/saved.

Oddly if you create and edit in root folder, it saves in the souce 1 instead of source 2 where it was created.

**Expected behaviour**
Create new files that are create and edited at their respective directory paths.

**Additional context**
Uploading and editing text files throws the same error. (Did not record it)

Uploading and viewing works fine (tested with text files and images).

**How to reproduce?**
Follow the steps in video with below configuration. (And I am using Raspberry Pi 4 so arm64 docker image)

```yaml
services:
  filebrowser:
    image: gtstef/filebrowser
    container_name: quantum
    restart: unless-stopped
    volumes:
      - ./config.yml:/home/filebrowser/config.yaml
      - ./data:/data
      - ./abc:/abc
    ports:
      - 8900:80
```
Config.yaml edited from full configuration example. Edited sources to have only path and name to have the default settings and external and internal URLs.

```yaml
...
  sources:
    - path: "/data"
      name: data
   # - path: "."
   #   name: backend
    - path: "/abc"
      name: Abc
  externalUrl: 'http://100.76.89.7:8900'
  internalUrl: 'http://100.76.89.7:8900'
...
```
