### ISSUE TITLE
Sources, scopes and defaultUserScope are bugged when setting for new user

### ISSUE THREAD

**Issue by BaccanoMob** [gtsteffaniak/filebrowser#537]
**Description**

From [wiki](https://github.com/gtsteffaniak/filebrowser/wiki/Configuration#default-source-configuration),

> When `createUserDir` is true, the `defaultUserScope` is the base directory.

(above quote is slightly modified but the context is the same)

**Expected behaviour**
Create `defaultUserScope` directory (aka base directory) in source if it does not exist before creating new user's directory.

**What is happening instead?**
Uses "" instead, that is, it uses root path of source instead.

**Additional context**
Workaround is it to make sure `defaultUserScope` path exists beforehand.

**How to reproduce?**
Just put an invalid path in `defaultUserScope` and create a new user.

By the way, this was the configuration of the source.

```yaml
...
    - path: "/data"
      name: data
      config:
        defaultUserScope: "/home" # include leading slash
        defaultEnabled: true
        createUserDir: true
...
```
