### ISSUE TITLE
Authelia OIDC setup

### ISSUE THREAD

**Issue by bunkerman** [gtsteffaniak/filebrowser#575]
Hello,

the OIDC login with authelia doesn't work.
I get this error:
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is…erwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered 'redirect_uris'.
(When I google the error I get for example that https://github.com/authelia/authelia/issues/5074)

Here are my confiog snippets
filebrowser quantum:
```
auth:
  methods:
    password:
      enabled: false # set to false if you only want to allow OIDC
    oidc:
      enabled: true
      clientId: "xxx"
      clientSecret: "xxx"
      authorizationUrl: https://auth.example.com/api/oidc/authorization/
      tokenUrl: https://auth.example.com/api/oidc/token/
      userInfoUrl: https://auth.example.com/api/oidc/userinfo/
      scopes: "email openid profile"
```

Authelia:
```
      - client_id: xxx
        client_name: filebrowser
        client_secret: xxx
        public: false
        authorization_policy: two_factor
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://file.browser.com/api/auth/oidc/login
        userinfo_signing_algorithm: none
        token_endpoint_auth_method: client_secret_basic
```

Is the redirect uri correct, because it's not documented?

**Comment by gtsteffaniak** [comment]
Hey thanks for opening this issue with your examples -- I only tested this with authentik and after searching I see authelia has a few extra requirements that need to be added.

Not to worry, these requirements can be done in a quick update to add authelia support. 

I will also add an authelia config example later too. but from my search, the extra things needed:

1.  bearer token requirement 
2. authz added to scopes

Sorry for the delay in support for all the oidc applications, I didnt know which needed special coverage and didn't want to test them all :)

**Comment by bunkerman** [comment]
Cool, thanks a lot and really appreciate your efforts. I think the most selfhosters use  authentik and authelia.

**Comment by gtsteffaniak** [comment]
Yeah I just assumed all the right parts were there for any oidc provider, I didn't realize there were a few extra steps for some. I'll just have to test locally and make sure it works for both of those.

Maybe other providers too, but I'll let people open issues if another kinda doesn't work.

**Comment by bunkerman** [comment]
If authelia works, I can share my config for documentation, if that helps others

**Comment by gtsteffaniak** [comment]
Yeah that could be helpful , I will also have a basic config example that I use as well, if yours is different that could be added to the wiki as well. I'll follow up when it's ready

**Comment by Rihan9** [comment]
Hi,
I'm using authelia just like bunkerman, can be this response that I'm receiving related to this isse?
```
{"status":500,"message":"failed to parse token response: invalid character '\u003c' looking for beginning of value"}
```

the url is:
```
/api/auth/oidc/callback?code=authelia_ac_3wJ9c3JR4Hny61FnEL53ruS7RclTeNK3tTrhRFcIx68.td-oxNZjOl9HaUtgQcyrPOZNuikNe4l_f5dBrD6CgX0&iss=https%3A%2F%2Fauth.mydomain&scope=email+openid+profile&state=fx7p0lf3s575nvjb
```

If not I'll open a new issue

**Comment by gtsteffaniak** [comment]
It could be, let's keep it in this issue for now. I'll test this out soon and have it fixed by this weekend.

I expect your issue will be fixed too, but if not you can update this issue

**Comment by gtsteffaniak** [comment]
Ok I think I added the bones needed for authelia to work. But authelia is not too easy to setup like authentik, I will need some help confirming it works in v0.7.1 beta and some example configs that you can confirm works for our documentation.

If you use v0.7.1-beta -- please enable debug logging and post any logs that you see during an authentication attempt.

Here is an example authelia config ([based on the nexcloud config](https://www.authelia.com/integration/openid-connect/nextcloud/)) I think mostly matches what you will need:

```
identity_providers:
  oidc:
    jwks:
      - key_id: 'example'
        algorithm: 'RS256'
        use: 'sig'
        key: <required>
        certificate_chain: <required>
    cors:
      endpoints: # not sure
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
        - 'userinfo'
    clients:
      - client_id: 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69'
        client_name: 'Filebrowser Client'
        client_secret: 'UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh'
        public: false # not sure
        authorization_policy: 'two_factor' # not sure
        require_pkce: true
        pkce_challenge_method: 'S256' # not usre
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        redirect_uris:
          - 'http://filebrowser/files/'
          - 'http://filebrowser/api/login/oidc/callback'
        grant_types:
          - 'authorization_code' # required
        userinfo_signed_response_alg: 'none' # not usre
        token_endpoint_auth_method: 'client_secret_basic' # not sure
```

Then a mandatory filebrowser configuration with values from the discovery URL, for example `https://authelia.localhost.com/.well-known/openid-configuration`

```
auth:
    oidc:
      enabled: true
      clientId: "xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69"
      clientSecret: "UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh"
      authorizationUrl: http://authelia.localhost.com/application/o/authorization/
      tokenUrl: http://authelia.localhost.com/application/o/token/
      userInfoUrl: http://authelia.localhost.com/application/o/userinfo/
      scopes: "email openid profile"
      jwksUrl: http://authelia.localhost.com/application/o/jwks/
```

In a later change, once we confirm these details, I think I'll be able to add auto-configuration based on the well-known host, but for now it's manual.

**Comment by bunkerman** [comment]
Mines not working:
From the filebrowser log
```
2025/05/09 10:57:29 [WARN ] middleware.go:310: GET     | 401 | 172.17.160.1:59044 |              | 1ms          | "/api/users?id=self"
2025/05/09 10:57:29 [WARN ] middleware.go:310: GET     | 302 | 172.17.160.1:59044 |              | 1ms          | "/api/auth/oidc/login?redirect=%2Ffiles%2F"
```

Alslo my OIDC urls are different:
instead of auth.com/application/o/authorize mine is auth.com/api/oidc/auhtorization 
like described here https://www.authelia.com/integration/openid-connect/introduction/#discoverable-endpoints

**Comment by gtsteffaniak** [comment]
I didn't think the changes in 0.7.1 would make it work, it will give me the info needed to update it if you add debug logging and the jwks url.

So try two things using an authelia server that works for other applications:

1) [enable debug logging ](https://github.com/gtsteffaniak/filebrowser/wiki/Logging#enable-debug-logging)
2) make sure to configure the jwks url (and other url info ) from the authelia well known config.
3) make sure all urls end with a "/" like `jwksUrl: https://auth.com/api/oidc/jwks/`

**Comment by Rihan9** [comment]
Sorry, I'm really busy at work, I need at least another day before having the time to check it. However, just one thing. The authorization url for athelia should be .../authorization not ../authorize

**Comment by bunkerman** [comment]
I did enable dbug logs. But the error log is the same as posted before and Authelia still gives the error as in my initial post.
the jwks uri is https://auth.example.com/jwks.json

**Comment by Rihan9** [comment]
Hi,
I was finally able to made a test, hope it helps.

here the related log lines:
```
2025/05/09 16:54:59 [INFO ] middleware.go:310: GET     | 302 | 172.20.0.5:52490 |              | 0ms          | "/api/auth/oidc/login"
2025/05/09 16:54:59 [DEBUG] auth.go:412: failed to parse token response: invalid character '<' looking for beginning of value
2025/05/09 16:54:59 [ERROR] middleware.go:310: GET     | 500 | 172.20.0.5:52490 |              | 40ms         | "/api/auth/oidc/callback?code=authelia_ac_i9wnFHtt2xPmKHVHWtUGyHgOBulNmZ0YFQl5v7D_MAs.E7AdL5AckedgnfQMFx_2enYayl0m_TaNr4b4WhMknig&iss=https%3A%2F%2Fauth.mydomain&scope=email+openid+profile&state=diyguylkhtaxpinb%3A"
2025/05/09 16:54:59 [INFO ] middleware.go:310: GET     | 200 | 172.20.0.5:52490 |              | 0ms          | "/favicon.ico"

```

here the related log lines on authelia:
```
time="2025-05-09T17:01:41Z" level=error msg="Authorization Response for Request with id 'fe675a3a-b03d-4912-8832-234ba3fd8454' on client with id '{{OMITTED}}' using policy 'one_factor' could not be created: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Clients must include a 'code_challenge' when performing the authorize code flow, but it is missing. The client with id '{{OMITTED}}' is registered in a way that enforces PKCE." method=GET path=/api/oidc/authorization remote_ip={{OMITTED}}
```

here the response screenshot:

![Image](https://github.com/user-attachments/assets/022d701a-080b-451a-b288-38711f2ac090)

here my configuration on FileBrowser Quantum:
```
auth:
    oidc:
      enabled: true
      clientId: "{{OMITTED}}"
      clientSecret: "{{OMITTED}}"
      authorizationUrl: https://auth.mydomain/api/oidc/authorization/
      tokenUrl: https://auth.mydomain/oauth2/token/
      userInfoUrl: https://auth.mydomain/oauth2/userinfo/
      jwksUrl: https://auth.mydomain/application/o/jwks/
      scopes: "email openid profile"
```

here my configuration on authelia:
```
clients:
      - client_name: 'quantum-filebrowser'
        client_id: '{{OMITTED}}'
        client_secret: '{{OMITTED}}'
        public: false
        require_pkce: true
        pkce_challenge_method: 'S256'
        authorization_policy: 'one_factor'
        consent_mode: pre-configured
        pre_configured_consent_duration: 75d
        redirect_uris:
          - 'https://files.mydomain/api/auth/oidc/login'
          - 'https://files.mydomain/api/auth/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        id_token_signed_response_alg: 'RS256'
        token_endpoint_auth_method: 'client_secret_basic'
```


I made another tests without enforcing pkce (commenting out the rows pkce_challenge_method and require_pkce) and no error are showing in the authelia log. @bunkerman maybe you can give it a try

**Comment by gtsteffaniak** [comment]
Thanks @Rihan9 for those logs -- that's very helpful. 

@bunkerman **Please try on v0.7.2** with redirect_urls added, see if you hit the same token format error.

There's probably a different logic I need to create for the response based on what is offered in the redirect.

If `one_factor` vs `two_factor`, for example. Or the PKCE type, I'll need to read up on OIDC docs to handle everything properly.

As for the OP's original issue:
> redirect_uri parameter does not match any of the OAuth 2.0 Client's pre-registered 'redirect_uris'

It's strange, I configured this for Authentik, which requires `redirect_uri` and Authelia requires `redirect_uris`, apparently only sometimes. Maybe it depends on if there's more than one configured:

```
        redirect_uris:
          - 'http://filebrowser/files/'
          - 'http://filebrowser/api/login/oidc/callback'
```

for 0.7.2 I added to pass both -- just in case :)

The good news here is, while I don't have authentik jwks setup locally, when I try to enable I get the same invalid token character issue -- which means I can probably replicate this and solve it for at least @Rihan9 or whenever sees that.

**Comment by gtsteffaniak** [comment]
So , I think we are almost there for authelia.

@Rihan9 example shows authelia did succeed on login and redirect back to filebrowser, but the jwks token parsing still needs adjustments. Filebrowser didn't know how to properly handle the successful authelia response.

Authentik doesn't require the extra jwks step authelia needs, but I think I can configure my authentik test setup to attempt JWKS machine-to-machine validation. I'll keep this issue posted.

If anyone else has additional settings, insight, or logs , feel free to post here.

**Comment by qskousen** [comment]
Hi! I'm also interested in getting Authelia working. 

I'm using `:dev` container image (pulled a few minutes ago). Here is my Authelia setup:

```
      - client_id: '<seceret-id>'
        client_name: 'FileBrowser Quantum'
        client_secret: '<secret-hash>'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://<filebrowser-domain>/api/auth/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        grant_types:
          - 'authorization_code'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
```

Here's my filebrowser config:

```
auth:
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      clientId: "filebrowser-quantum"
      clientSecret: "<secret-pass>"
      authorizationUrl: "https://<authelia-domain>/api/oidc/authorization"
      tokenUrl: "https://<authelia-domain>/api/oidc/authorization"
      userInfoUrl: "https://<authelia-domain>/api/oidc/userinfo"
      scopes: "openid profile email"
      jwksUrl: "https://<authelia-domain>/jwks.json"
```

I'm successfully using this Authelia server for other things, so I know it's working correctly.

When navigating to `<filebrowser-domain>` it correctly redirects me to Authelia, when I can log in and see the requested claims correctly. When I accept on Authelia, it navigates to the callback URL correctly, but loads forever. During this time, filebrowser is spamming Authelia about 15-20 times per second for several minutes in an attempt to authenticate, apparently in an endless loop until something crashes. The Authelia log shows this:

```
May 09 16:35:01 authelia authelia[52256]: time="2025-05-09T16:35:01Z" level=error msg="Authorization Request failed with error: The authorization server does not support obtaining a token using this method. `The request is missing the 'response_type' parameter." method=POST path=/api/oidc/authorization remote_ip=<remote-ip> stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:46           OpenIDConnectAuthorization\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:114 RegisterOpenIDConnectRoutes.NewHTTPToAutheliaHandlerAdaptor.func9\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66                            RegisterOpenIDConnectRoutes.(*BridgeBuilder).Build.func2.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105                          SecurityHeadersNoStore.func1\ngithub.com/valyala/fasthttp@v1.59.0/userdata.go:57                                           (*userData).Get\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                           SecurityHeadersBase.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/cors.go:216                             RegisterOpenIDConnectRoutes.(*CORSPolicy).Middleware.func10\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14                       handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                            RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2380                                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:225                                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:197                                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                                     goexit"
```
And the filebrowser log shows this:

```
2025/05/09 16:37:22 [ERROR] middleware.go:310: GET     | 500 | 10.88.0.1:59730 |              | 213314ms     | "/api/auth/oidc/callback?error=unsupported_response_type&error_description=The+authorization+server+does+not+support+obtaining+a+token+using+this+method.+%60The+request+is+missing+the+%27response_type%27+parameter.&iss=https%3A%2F%2F<authelia-domain>"
2025-05-09T12:37:22.494502587-04:00 stdout F 2025/05/09 16:37:22 [DEBUG] auth.go:394: failed to send token request: Post "https://<filebrowser-domain>/api/auth/oidc/callback?error=unsupported_response_type&error_description=The+authorization+server+does+not+support+obtaining+a+token+using+this+method.+%60The+request+is+missing+the+%27response_type%27+parameter.&iss=https%3A%2F%2F<authelia-domain>": unexpected EOF
```

Edit to note that I initially tried with `latest`, and pulled `dev` to test with when I saw this thread.

**Comment by gtsteffaniak** [comment]
That's very helpful, thanks I'll take a look at all of this today. I'm sure I'll have it fixed by this weekend sometime.

For the moment latest image should be updated with all the changes from dev, but I may need your help confirming a dev image works when I believe I have it fixed!

**Comment by qskousen** [comment]
> If `one_factor` vs `two_factor`, for example. Or the PKCE type, I'll need to read up on OIDC docs to handle everything properly.

Just to note for you that the `one_factor` vs `two_factor` is just an Authelia thing - determining if the user needs to be logged in with 2fa in order to access the requested resource. Not something that would matter to Filebrowser.

**Comment by bunkerman** [comment]
Is it a problem if I use the same username for normal filebrowser login as for the OIDC login? This is the case in my setup.

**Comment by gtsteffaniak** [comment]
With 0.7.2, I allow cross method login again, the the future some time it will be restricted again.

There is a security issue by allowing login from different methods. One person may have the password and another may have the oidc login info.

But anyways for now it's allowed. I think I have all the info I need to fix it, I'll post when I believe 0.7.3 dev version is ready with the fix so you guys can double check it with your configs.

**Comment by gtsteffaniak** [comment]
If anyone has filebrowser deployed via docker, can you test this dev image: `gtstef/filebrowser:0.7.3-dev`

You'll need to update the config, now filebrowser requires the issuerUrl to autoconfigure the rest:

For example if your config was:
```
    oidc:
      enabled: true
      clientId: "vyBrzOmcrU3OokiWEZoObdGBscw0eYPNJauBtOJr"
      clientSecret: "gIMKbkEcckUhlGrnE2Vxi8eZhEcfxQqfwFgM0ATzk4DciHGrW2YRtQfqcpRTsmzrxEETkKvZ8yeK3sfoXnUV1IQTzqK7wxw3lEMtmeXi5clj0h7nH1rVGFq2Q3HL8zUe"
      authorizationUrl: http://localhost/application/o/authorize/
      tokenUrl: http://localhost/application/o/token/
      userInfoUrl: http://localhost/application/o/userinfo/
      scopes: "email openid profile"
```
it should now autoconfig with:

```
    oidc:
      enabled: true
      clientId: "vyBrzOmcrU3OokiWEZoObdGBscw0eYPNJauBtOJr"
      clientSecret: "gIMKbkEcckUhlGrnE2Vxi8eZhEcfxQqfwFgM0ATzk4DciHGrW2YRtQfqcpRTsmzrxEETkKvZ8yeK3sfoXnUV1IQTzqK7wxw3lEMtmeXi5clj0h7nH1rVGFq2Q3HL8zUe"
      issuerUrl: http://localhost/application/o/filebrowser/
      scopes: "email openid profile"
```

I am now using an external library to handle it in v0.7.3, so your testing would be appreciated.

**Comment by qskousen** [comment]
I've tested it, setting `issuerUrl: https://<authelia-domain>/`, but when it gets to my authorizing the request and redirecting back to filebrowser, filebrowser shows a JSON error of `{"status":500,"message":"invalid request params"}`.

The application log shows:

```
2025/05/14 01:06:29 [INFO ] middleware.go:310: GET     | 200 | 10.88.0.1:36986 |              | 0ms          | "/"
2025/05/14 01:06:29 [WARN ] middleware.go:310: GET     | 401 | 10.88.0.1:37000 |              | 0ms          | "/api/users?id=self"
2025/05/14 01:06:31 [INFO ] middleware.go:310: GET     | 302 | 10.88.0.1:37000 |              | 0ms          | "/api/auth/oidc/login"
2025/05/14 01:06:47 [DEBUG] auth.go:377: ID token found in token response, attempting verification.
2025/05/14 01:06:47 [DEBUG] auth.go:394: ID Token verified and claims decoded: map[amr:[pwd kba otp mfa] at_hash:<hash-here> aud:[filebrowser-quantum] auth_time:1.747184802e+09 azp:filebrowser-quantum exp:1.747188407e+09 iat:1.747184807e+09 iss:https://<authelia-domain> jti:<token-here> rat:1.747184791e+09 sub:<sub-here>]
2025/05/14 01:06:47 [DEBUG] auth.go:417: Essential claims found in ID token.
2025/05/14 01:06:47 [ERROR] middleware.go:310: GET     | 500 | 10.88.0.1:37000 |              | 1577ms       | "/api/auth/oidc/callback?code=authelia_ac_<token-here>&iss=https%3A%2F%2F<authelia-domain>&scope=openid+profile+email&state=acqx89211m2gcz8y%3A"

```

I'm not sure what is sensitive data in that output so I edited out some things in \<brackets\>.

**Comment by gtsteffaniak** [comment]
Oh awesome! It works , I just missed a change in my redirect code.

But from those logs I can tell it fully authenticated. The error you see is from my code extracting the redirect url which authelia didn't provide so it failed.

For now I will just have it redirect to the /files url.

I'll have this fixed tomorrow, thanks for checking.

**Comment by nS-Gecko** [comment]
I'm testing the same configuration with Authelia + Traefik + file browser + gtstef/filebrowser:0.7.3-dev.
I may have something else not properly configured but I'm facing this error from filebrowser :

`[FATAL] Error validating OIDC auth: url 'http://auth.domain.com/.well-known/openid-configuration' failed to create OIDC provider: Get "https://auth.domain.com/.well-known/openid-configuration/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority`

Is there any way to skip the certificate validation whatsoever at this moment ?

**Comment by qskousen** [comment]
> I may have something else not properly configured

You need to set the issuerURL to just the bare domain, i.e. `http://auth.domain.com`. it will add the `.well-known` stuff itself.

> Is there any way to skip the certificate validation whatsoever at this moment ?

The underlying `coreos/go-oidc` package [supports it](https://github.com/coreos/go-oidc/issues/321) but it's not currently exposed.

**Comment by gtsteffaniak** [comment]
It appears I can provide a custom context to the library that will allow insecure tls. Generally, the better solution would be to have self-signed certs locally to avoid this error. But I will add a skip TLS verify flag in oidc config.

**Comment by gtsteffaniak** [comment]
Ok should be all working now -- try doing a docker pull `gtstef/filebrowser:0.7.3-dev` to get the latest changes.

Btw you can now disable the certificate check in your config with:

```
    oidc:
      disableVerifyTLS: true
```

Would appreciate someone verifying its all working now.

**Comment by Rihan9** [comment]
for me, it works like a charm now. Many thanks @gtsteffaniak !!

**Comment by qskousen** [comment]
It works for me as well. Thank you!

**Comment by christaikobo** [comment]
Great news! Although I am still using proxy auth for filebrowser, I am using authelia for a lot of other apps and I am so happy to hear that it works now. 

The addition of OIDC is a very significant step forward, I feel like this project is closing in on a formal release version:)

**Comment by bunkerman** [comment]
Check, it works - excellent work!

here's my config:

Authelia:
```
      - client_id: xxx
        client_name: filebrowser
        client_secret: xxx
        public: false
        authorization_policy: two_factor
        scopes:
          - openid
          - email
          - profile
        grant_types:
          - 'authorization_code' # required
        redirect_uris:
          - https://files.example.com/api/auth/oidc/callback
        userinfo_signing_algorithm: none
        token_endpoint_auth_method: client_secret_basic
```
Filebrowser:
```
    oidc:
      enabled: true
      clientId: "xxx"
      clientSecret: "xxx"
      issuerUrl: "https://auth.example.com"
      scopes: "email openid profile"
```

**Comment by gtsteffaniak** [comment]
Adding to wiki, thank you!

**Comment by tomorrow-nf** [comment]
The wiki config doesn't seem to be working for me:

``failed to exchange token: oauth2: "invalid_client" "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The request was determined to be using 'token_endpoint_auth_method' method 'client_secret_post', however the OAuth 2.0 client registration does not allow this method."``

Simply changing to _post on authelia's end doesn't resolve it. Any ideas here?

**Comment by bunkerman** [comment]
> The wiki config doesn't seem to be working for me:
> 
> `failed to exchange token: oauth2: "invalid_client" "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The request was determined to be using 'token_endpoint_auth_method' method 'client_secret_post', however the OAuth 2.0 client registration does not allow this method."`
> 
> Simply changing to _post on authelia's end doesn't resolve it. Any ideas here?

Have you tried my config? https://github.com/gtsteffaniak/filebrowser/issues/575#issuecomment-2889188044

**Comment by tomorrow-nf** [comment]
> Have you tried my config? [#575 (comment)](https://github.com/gtsteffaniak/filebrowser/issues/575#issuecomment-2889188044)

Yep, my config is identical to this on both the filebrowser and authelia ends. Not quite sure what's missing here.

**Comment by gtsteffaniak** [comment]
Seems like an authelia config issue related to the auth method:

`token_endpoint_auth_method: client_secret_post`

When it should be:

`token_endpoint_auth_method: client_secret_basic`

**Comment by tomorrow-nf** [comment]
> Seems like an authelia config issue related to the auth method:
> 
> `token_endpoint_auth_method: client_secret_post`
> 
> When it should be:
> 
> `token_endpoint_auth_method: client_secret_basic`

Unfortunately not the case. Here's the full client config:

```
- client_id: '***'
        client_name: 'filebrowser'
        client_secret: '***'
        public: false
        authorization_policy: 'two_factor'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        grant_types:
          - 'authorization_code'
        redirect_uris:
          - 'https://files.domain.tld/api/auth/oidc/callback'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
```

And the filebrowser config:

```
auth:
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      clientId: "***"
      clientSecret: "***"
      issuerUrl: "https://auth.domain.tld"
      scopes: "email openid profile"
      createUser: true
      adminGroup: "admins"
```
