### ISSUE TITLE
defaultUserScope is not respected

### ISSUE THREAD

**Issue by christaikobo** [gtsteffaniak/filebrowser#589]
**Description**
```
  sources:
    - name: "Default"
      path: "/source"
      config:
        defaultUserScope: "/users"
        defaultEnabled: true
        createUserDir: true
```
With the above config, when creating user like this:
![Image](https://github.com/user-attachments/assets/0c3996e6-e2e6-4974-bce8-dd46008264ea)

I got scope like this:

![Image](https://github.com/user-attachments/assets/c814b478-44de-47b5-92db-e9c101c10b59)

**Expected behaviour**
User `test` should have scope of `/users/test`

**What is happening instead?**
User `test` has scope of `/test`

**How to reproduce?**
Use above config, create new user without specifying scope.
