### ISSUE TITLE
Can't login with admin account

### ISSUE THREAD

**Issue by TaylanTatli** [gtsteffaniak/filebrowser#594]
**Description**
I want to log in with the admin account since I will be the only user. Therefore, I modified the config.yaml file as follows:

```
auth:
  tokenExpirationHours: 2
  methods:
    noauth: false
    password:
      enabled: true
      minLength: 5
      signup: false
  adminUsername: "TaylanTatli"
  adminPassword: "redacted"
```

However, when I try to log in, I get the "Wrong credentials" error. What am I doing wrong? If I log in with noauth: true, I see an admin user, but the username is not my username. When I try to log in with the username "admin" and the password I set, it doesn't work. I also tried logging in with the username "admin" and the password "admin", but I still can't log in. I tried by deleting the database, still same. I set it up from scratch, but the issue still persists.

**Expected behaviour**
I should be able to log in with the admin user credentials I set.

**What is happening instead?**
I get the "Wrong credentials" error

**Additional context**
Using 0.7.0-beta image.

**Comment by gtsteffaniak** [comment]
There's a couple reasons:

1) you are running with a database file that already had an admin user with a different password.

2) you didn't run the program with the config properly?

You can do a [password reset ](https://github.com/gtsteffaniak/filebrowser/wiki/CLI#perform-password-reset) for a user (make sure to specify the config if it's not simply ./config.yaml)

You could also delete the database if it's not that big of a deal and you just started.

**Comment by TaylanTatli** [comment]
I used the compose from the wiki. The following was provided for the database:
`./database:/home/filebrowser/database`

Since there is no folder named `/home/filebrowser/database`, it was created as `/home/filebrowser/database.db`. Now, I have mounted it as `/home/filebrowser/database.db`. My username appears (when I start with `noauth: true`), but when I try to log in, I get the following error:
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
{"status":401,"message":"invalid token provided"}
```

Of course, I can reset the password since my username appears to be correct, but shouldn’t it work as initially configured?

My compose:
```
services:
  filebrowserQuantum:
    image: gtstef/filebrowser:0.7.0-beta
    container_name: filebrowserQuantum
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 85:80
    volumes:
      - /mnt:/srv
      - /SSD:/srv/SSD
      - /DATA:/srv/DATA
      - /SSD/AppData/filebrowserQuantum/config/config.yaml:/home/filebrowser/config.yaml
      - /SSD/AppData/filebrowserQuantum/database/database.db:/home/filebrowser/database.db
```

My config:
```
server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/srv"
      config:
        defaultEnabled: false
        createUserDir: false
userDefaults:
  preview:
    image: true
    popup: true
    video: false
    office: false
    highQuality: false
  darkMode: true
  disableSettings: false
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
auth:
  methods:
    noauth: false
    password:
      enabled: true
      minLength: 5
      signup: false
  adminUsername: "TaylanTatli"
  adminPassword: "redacted"
```

**Comment by TaylanTatli** [comment]
Now I opened the database.db file with a hex editor and verified my password by matching it with the bcrypt hash shown in the database, and it appears to be correct. I don't understand what the issue is.

**Comment by TaylanTatli** [comment]
I didn't want to spend more time on this, so I tried resetting my password, but I couldn't manage that either 😂. I logged in with `noauth: true` and changed my password from the user management section, but it didn’t work. Then, I tried running the command `./filebrowser set -u TaylanTatli,newpassword` inside the container, but I got the error `[FATAL] storm.Open path database.db: timeout`. I guess I have no luck with this.

**Comment by gtsteffaniak** [comment]
Database timeout means the db is already being accessed by another process. You'll need to kill all running processes before doing a database reset.

For reference, I constantly use the custom username password that you're using for testing. I'm sure it works, I bet you had an existing database with the default admin/admin set at some point.

**Comment by gtsteffaniak** [comment]
With docker I think that's tricky. Run it with `entrypoint: sh` to open a shell instead of starting the server

**Comment by TaylanTatli** [comment]
I always delete old databases before trying something new. Something's wrong I guess but couldn't find it, sorry. For now I just set `FILEBROWSER_ADMIN_PASSWORD` variable.

**Comment by gtsteffaniak** [comment]
I'll take a closer look at this and test it

**Comment by gtsteffaniak** [comment]
Works on my testing with a fresh database

```
auth:
  adminUsername: "graham"
  adminPassword: "graham"
```

**Comment by Jaumoso** [comment]
Hey, @gtsteffaniak hope you are doing great. I had the same problem as @TaylanTatli, I could not log in using my own default credentials for the admin user. Turns out, you can't use the character "%" in the password. I don't know if it happens with any other character.

![Image](https://github.com/user-attachments/assets/e0eeaec0-c6ce-45b5-8fde-ff451d32a754)

Added console output for the login parameters in the backend:
![Image](https://github.com/user-attachments/assets/7acbf638-0ae5-4b7f-9bd8-e98414c324f3)

Output of the password with and without "%".
![Image](https://github.com/user-attachments/assets/4913a027-185e-4556-8904-eef6406bbf03)

If the password does not contain "%" I can authenticate.

The parameters are not encoded, that's probably the problem.

**Comment by gtsteffaniak** [comment]
This is very helpful info. Thanks I'll test what characters are supported and restrict passwords.

Btw feel free to use the reset admin password on startup feature to quickly update passwords when an admin user gets locked out.

**Comment by gtsteffaniak** [comment]
```
auth:
  adminUsername: admin                    # the username of the admin user. If not set, the default is "admin".
  adminPassword: admin                    # the password of the admin user. If not set, the default is "admin".
  resetAdminOnStart: false                # if set to true, the admin user will be reset to the default username and password on startup.
```
