### ISSUE TITLE
Proxy auth broken

### ISSUE THREAD

**Issue by christaikobo** [gtsteffaniak/filebrowser#609]
Just tried new 0.7.1-beta, and proxy auth is completely broken.

Whichever user I login with, I am met with an empty setting menu and file panel, 

![Image](https://github.com/user-attachments/assets/1dc5fa32-b74e-4f9b-ae54-e7d90e025326)

And while clicking on the change view mode at top right, I got 403 user *** is not allowed to login with proxy authentication error message. 

I read the changelog and it seems that you are enforcing user auth type. But old users are all password users, because you cannot create a user without password in filebrowser. And the initial admin user is always a password user. Also I don't like the idea of creating user automatically so I set 
```
auth:
  methods:
    proxy:
      enabled: true
      header: "Remote-User"
      createUser: false
```
specifically to not create user from my proxy auth. 

One idea I have is to only enforce between OIDC and non-OIDC user auth types.
