### ISSUE TITLE
Align the conditions for showing "Change password" and password input box in user management

### ISSUE THREAD

**Issue by christaikobo** [gtsteffaniak/filebrowser#619]
**Description**
Right now I have disabled password auth:
```
auth:
  methods:
    proxy:
      enabled: true
      header: "Remote-User"
      createUser: false
    password:
      enabled: false
      minLength: 16
    noauth: false
```
And I have a legacy password user, when trying to edit the user, this is shown:

![Image](https://github.com/user-attachments/assets/17242f05-01a7-47cc-b123-98876fadccef)
I guess because password auth is disabled, the password input box is completely hidden, however the "change password" toggle box is still present, presumably because the user is a password user. 

**Expected behaviour**
Either: when password auth is disabled, regardless of the user type, both "change password" checkbox and the password input box is hidden.

Or: when user is password user, regardless of the auth setting, show "change password" checkbox and the password input box; when user is not a password user, regardlesss of the auth setting, hide "change password" checkbox and the password input box.

I prefer the latter, because it feels more logical.
