### ISSUE TITLE
Help setting Default user/password

### ISSUE THREAD

**Issue by edersong** [gtsteffaniak/filebrowser#625]
**Description**
Deployed following the instructions, but default user/password is not working.

**Expected behaviour**
Login with default user/password for the first login.

**What is happening instead?**
Reports user or password error
Nothing is reported on the container logs.

**Additional context**
Tried to update admin user thru command but got the following error:
```
/home/filebrowser # ./filebrowser set -u admin,admin -a
2025/05/11 11:24:18 [FATAL] storm.Open path /home/filebrowser/database/database.db: timeout
``` 

**How to reproduce?**
Docker compose:
```
services:
  filebrowser:
    image: gtstef/filebrowser:latest
    container_name: filebrowser_quantum
    volumes:
      - /mnt/:/srv
      # optional if you want db to persist - configure a path under "database" dir in config file.
      - /volumes/filebrowser_quantum/database:/home/filebrowser/database
      - /volumes/filebrowser_quantum/config.yaml:/home/filebrowser/config.yaml
      - /volumes/filebrowser_quantum/tmp/:/home/filebrowser/tmp/
#    ports:
#      - '80:80'
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
``` 
config.yaml
```
server:
  port: 80
  baseURL:  ""
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/srv"
  database: "/home/filebrowser/database/database.db"
userDefaults:
  preview:
    image: true
    popup: true
    video: false
    office: false
    highQuality: false
  darkMode: true
  disableSettings: false
  singleClick: false
  permissions:
    admin: true
    modify: false
    share: false
    api: false

auth:
  methods:
    noauth: false
    password:
      enabled: true
``` 

**Files**
Log from container:
```
filebrowser_quantum  | 2025/05/11 08:54:09 Initializing FileBrowser Quantum (v0.7.2-beta)
filebrowser_quantum  | 2025/05/11 08:54:09 Using Config file        : config.yaml
filebrowser_quantum  | 2025/05/11 08:54:09 Auth Methods             : [Password]
filebrowser_quantum  | 2025/05/11 08:54:09 Creating new database    : /home/filebrowser/database/database.db
filebrowser_quantum  | 2025/05/11 08:54:09 Sources                  : [srv: /srv]
filebrowser_quantum  | 2025/05/11 08:54:09 Running at               : http://localhost/
filebrowser_quantum  | 2025/05/11 08:54:10 initializing index: [srv]
filebrowser_quantum  | 2025/05/11 08:54:16 GET     | 200 | 172.19.0.2:56706 |              | 2ms          | "/"
filebrowser_quantum  | 2025/05/11 08:54:16 GET     | 200 | 172.19.0.2:56708 |              | 3ms          | "/static/assets/index-1EamZqCf.js"
filebrowser_quantum  | 2025/05/11 08:54:16 GET     | 200 | 172.19.0.2:56724 |              | 1ms          | "/static/assets/i18n-B7OPuQrh.js"
filebrowser_quantum  | 2025/05/11 08:54:16 GET     | 200 | 172.19.0.2:56732 |              | 3ms          | "/static/assets/index-CAURcy0j.css"
filebrowser_quantum  | 2025/05/11 08:54:17 GET     | 401 | 172.19.0.2:56748 |              | 0ms          | "/api/users?id=self"
filebrowser_quantum  | 2025/05/11 08:54:18 GET     | 200 | 172.19.0.2:56750 |              | 3ms          | "/static/assets/icons-D-x-0Q06.woff2"
filebrowser_quantum  | 2025/05/11 08:54:18 GET     | 200 | 172.19.0.2:56760 |              | 1ms          | "/static/assets/medium-latin-qoGZqeje.woff2"
filebrowser_quantum  | 2025/05/11 08:54:18 GET     | 200 | 172.19.0.2:56762 |              | 1ms          | "/static/img/icons/android-chrome-192x192.png"
filebrowser_quantum  | 2025/05/11 08:54:24 POST    | 200 | 172.19.0.2:56768 |              | 86ms         | "/api/auth/login"
filebrowser_quantum  | 2025/05/11 08:54:24 GET     | 401 | 172.19.0.2:56780 |              | 0ms          | "/api/users?id=self"
filebrowser_quantum  | 2025/05/11 08:58:46 Index assessment         : [srv] complexity=complex directories=115150 files=360895
```

**Comment by gtsteffaniak** [comment]
This happens because you may have set it up with one password and change it later.

Doing a password reset is tricky with docker because you have to alter the docker config. I'll update the cli readme to give an example how to reset the password with docker.

Also this isn't the first time this has happened, and I understand it's tricky to do especially with docker. So I will add a config option to always reset default admin password on startup so it will get set to whatever is in config.

**Comment by gtsteffaniak** [comment]
Can you try using this docker specific instructions I added on the wiki?

https://github.com/gtsteffaniak/filebrowser/wiki/CLI#using-cli-with-docker

**Comment by gtsteffaniak** [comment]
And based on the config ,  and the logs, should be admin/admin since nothing was set.

**Comment by edersong** [comment]
Thank you for the suggestions.
I was able to change password, but it still not working.
I guess that my db that is something wrong with my compose.yaml or config.yaml, but didn't realize what is wrong.
Here are my updated compose file and config file:

Docker compose:
```
services:
  filebrowser:
    image: gtstef/filebrowser:latest
    container_name: filebrowser_quantum
    volumes:
      - /mnt/:/srv
      - /volumes/filebrowser_quantum/database.db:/home/filebrowser/database.db
      - /volumes/filebrowser_quantum/config.yaml:/home/filebrowser/config.yaml
      - /volumes/filebrowser_quantum/tmp:/home/filebrowser/tmp
#    ports:
#      - '80:80'
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
``` 

config.yaml
```
server:
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/srv"
userDefaults:
  preview:
    image: true
    popup: true
    video: true
```

**Comment by edersong** [comment]
Thank you for the suggestions.
I was able to change password, but it still not working.
I guess that is something wrong with my `compose.yaml` or `config.yaml`, but didn't realize what is wrong.
Here are my updated compose file and config file:

Docker compose:
```
services:
  filebrowser:
    image: gtstef/filebrowser:latest
    container_name: filebrowser_quantum
    volumes:
      - /mnt/:/srv
      - /volumes/filebrowser_quantum/database.db:/home/filebrowser/database.db
      - /volumes/filebrowser_quantum/config.yaml:/home/filebrowser/config.yaml
      - /volumes/filebrowser_quantum/tmp:/home/filebrowser/tmp
#    ports:
#      - '80:80'
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
``` 

config.yaml
```
server:
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/srv"
userDefaults:
  preview:
    image: true
    popup: true
    video: true
```
