### ISSUE TITLE
Custom OIDC Provider Fails for Filebrowser Authentication

### ISSUE THREAD

**Issue by baur** [gtsteffaniak/filebrowser#631]
My Custom [Node OIDC provider](https://github.com/panva/node-oidc-provider) works for [Grafana ](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/) and [Planka](https://docs.planka.cloud/docs/configuration/oidc) but fails for Filebrowser, returning a 500: invalid request params error.

I'm swithced off PKCE on server side and not using ssl

Server-Side Configuration:

```
  const users = {
    User1: {
      sub: "2b16d558-8d37-46b9-bdf9-7b4721acd434",
      email: "User1@mail.qz",
      password: "123123",
      name: "User Name",
      username: "User1"
    },
...

const clients = [
    {
      client_id: "filebrowser-client",
      client_secret: "AC46DF90-9D5C-42FD-B274-E177D9C85126",
      redirect_uris: ["http://localhost:3001/api/auth/oidc/callback"],
      response_types: ["code"],
      grant_types: ["authorization_code"],
      token_endpoint_auth_method: "client_secret_post",
      pkce_methods: ["S256"],
    },
...
```

Client-Side Configuration (Filebrowser):
```
    oidc:            
      enabled: true 
      clientId: "filebrowser-client"
      clientSecret: "AC46DF90-9D5C-42FD-B274-E177D9C85126"
      authorizationUrl: "http://localhost:4000/auth" 
      tokenUrl: "http://localhost:4000/token"
      userInfoUrl: "http://localhost:4000/me"
      scopes: "openid profile email"
      userIdentifier: "username"
      jwksUrl: ""
```

Error (Client-Side):

```
{status: 500, message: "invalid request params"}
message: "invalid request params"
status: 500
```
Screenshots:

![Image](https://github.com/user-attachments/assets/6c28fb20-398a-489a-992d-262e4ba0fb10)

![Image](https://github.com/user-attachments/assets/125c303b-b57e-415c-9664-7034ce73a8cd)

Server-Side Logs:

```
Simple Express app listening on port 4000!
2025-05-09T21:52:24.655Z [info]: Finding account for id: User1
2025-05-09T21:52:24.656Z [info]: Returning account for User1
2025-05-09T21:52:28.626Z [info]: Finding account for id: User1
2025-05-09T21:52:28.627Z [info]: Returning account for User1
2025-05-09T21:52:28.629Z [info]: Authorization successful
2025-05-09T21:52:28.646Z [info]: Finding account for id: User1
2025-05-09T21:52:28.647Z [info]: Returning account for User1
2025-05-09T21:52:28.648Z [info]: Claims for user User1: {"sub":"2b16d558-8d37-46b9-bdf9-7b4721acd434","email":"User1@mail.qz","name":"User Name","username":"User1"}
2025-05-09T21:52:28.658Z [info]: Finding account for id: User1
2025-05-09T21:52:28.658Z [info]: Returning account for User1
2025-05-09T21:52:28.659Z [info]: Claims for user User1: {"sub":"2b16d558-8d37-46b9-bdf9-7b4721acd434","email":"User1@mail.qz","name":"User Name","username":"User1"}
2025-05-09T21:52:28.659Z [info]: Userinfo response: {"sub":"2b16d558-8d37-46b9-bdf9-7b4721acd434","name":"User Name","username":"User1","email":"User1@mail.qz"}
```

**Comment by baur** [comment]
createing same user with same password on Filebrowser not helped

**Comment by gtsteffaniak** [comment]
thanks for the additional provider to go on, I am working to fix authelia and I imagine this is the same issue. I'll keep you posted.

**Comment by gtsteffaniak** [comment]
if you are using docker, can you test this dev image: `gtstef/filebrowser:0.7.3-dev`

You'll need to update the config:

```
    oidc:            
      enabled: true 
      clientId: "filebrowser-client"
      clientSecret: "AC46DF90-9D5C-42FD-B274-E177D9C85126"
      issuerUrl: "http://localhost:4000/" 
      scopes: "openid profile email"
      userIdentifier: "username"
```
This should autoconfigure based on info from `http://localhost:4000/.well-known/openid-configuration`

I am now using an external library to handle it in v0.7.3, so your testing would be appreciated.

**Comment by auer1329** [comment]
EDIT: I had problems adjusting my configuration for v0.7.3. It was not clear to me what the issuer URL is for my Authentik instance, turns out I just had to look at my provider configuration page.

May be interesting for users with the same problems, I changed from

```
authorizationUrl: https://auth.domain.tld/application/o/authorize/
tokenUrl: https://auth.domain.tld/application/o/token/
userInfoUrl: https://auth.domain.tld/application/o/userinfo/
```

to

`issuerUrl: https://auth.domain.tld/application/o/filebrowser-quantum/`

Replace "filebrowser-quantum" in the URL with the slug you defined in the OIDC provider.

**Comment by baur** [comment]
Hi, I can't set up Docker , win env.


after 7.3 version
OIDC works 👍 

but works only with param `userIdentifier: "email"`

```
    oidc:     
      enabled: true
      clientId: "filebrowser-client"
      clientSecret: "AC46DF90-9D5C-42FD-B274-E177D9C85126"
      issuerUrl: http://localhost:4000
      scopes: "openid profile email"
      userIdentifier: "email"
```

![Image](https://github.com/user-attachments/assets/adcf7269-3d1a-4f36-beda-9ec5aed8224b)

without 
userIdentifier: "email"

I see client error:
{"status":500,"message":"no valid username found in ID token or UserInfo response from claims"}

Server response:

Userinfo response (/me'): {"sub":"7e7cbaeb-4470-4047-9cf6-958b327e8bb2","name":"User1 User1","username":"User1","email":"User1@User1.qz"}



username field (by default for userIdentifier) is exists,
