### ISSUE TITLE
Sign up does not work

### ISSUE THREAD

**Issue by BaccanoMob** [gtsteffaniak/filebrowser#648]
![Image](https://github.com/user-attachments/assets/a2e4c50c-4948-4f2d-9779-546fd527a411)

When checking the network tab, I see `Method not Allowed` in Response.

Part of config where I set signup as true.

```yaml
    password:
      enabled: true
      minLength: 5
      signup: true
```

Also, there is an error in [docs](https://github.com/gtsteffaniak/filebrowser/wiki/Configuration-And-Examples#auth-config-examples). It states below,

```yaml
auth:
  signup: false
```

When I tried this, I get `error unmarshaling YAML data: [20:3] unknown field "signup"`
