### ISSUE TITLE
OnlyOffice Download Failed

### ISSUE THREAD

**Issue by sugarfunk** [gtsteffaniak/filebrowser#650]
I have done everything I know to get the OnlyOffice integration to work. What am I doing wrong?

Every file results in this with no specific console errors except http loading on https. Which is odd because I set my OnlyOffice url with https. so not sure where the http comes from. Screenshot below

<img width="258" alt="Image" src="https://github.com/user-attachments/assets/88cbfbde-2e9b-4c68-a7cd-a64bd4966f14" />

<img width="350" alt="Image" src="https://github.com/user-attachments/assets/67d755a5-dfd6-4f81-8e13-7577ec7f29ec" />

My Docker Compose

```
services:
  filebrowser:
    image: gtstef/filebrowser
    ports:
      - 8088:80
    volumes:
      - /mnt/media:/media
      - /mnt/lts:/lts
      - ./database:/home/filebrowser/database
      - ./config/config.yaml:/home/filebrowser/config.yaml
    restart: unless-stopped
  onlyoffice:
    image: onlyoffice/documentserver
    environment:
      JWT_SECRET: xxxxxxxxxxxxxxxxxx
    ports:
      - 8089:80
networks: {}
```

My Config file
```
server:
  internalUrl: "http://192.168.1.55:8088/"
  externalUrl: "https://files.mydomain.com/"
  port: 80
  #baseURL: "/"
  database: "/database/database.db"
  logging:
  - output: stdout
    levels: "info|warning|error|debug"
  sources:
    - name: "Media"
      path: "/media"
    - name: "LTS"
      path: "/lts"

frontend:
  name: "MyCloud Drive"                     # "display name"
  disableDefaultLinks: false   # "disable default links in the sidebar"
  disableUsedPercentage: true # "disable used percentage for the sources in the sidebar"

integrations:
  office:
    url: "https://oo.mydomain.com"
    internalUrl: "http://192.168.1.55:8089"
    secret: xxxxxxxxxxxxxxxxxx
```
