### ISSUE TITLE
Proxy auth logout not clearing reverse proxy session

### ISSUE THREAD

**Issue by bonza-views** [gtsteffaniak/filebrowser#684]
Congrats on this project, you have done an amazing job. By far my favourite File Browser.

**Is your feature request related to a problem? Please describe.**
I'm using Proxy auth with an reverse SSO proxy (nginx/oauth2-proxy). Login works sweet, however the logout button in FileBrowser doesn't trigger a webserver request, logout just seems to all happen in the client. No webserver log entries are created when a user logs out. Without a specific logout URL for the reverse proxy to see, the reverse proxy cannot sign out, so the session variables are never cleared. This allows unauthorised users on the same machine to access data for another user by simply clicking the browser back button.

When using a reverse proxy with proxy auth, the sessions/cookies are managed by the reverse proxy instead of the web application. There needs to be a mechanism for the web app to inform the reverse proxy the user wants to logout.

**Describe the solution you'd like**
If the LOGOUT button created a HTTP request like "/logout", the reverse proxy session can be cleared.

**Describe alternatives you've considered**
I tried using the "/login" URL in the reverse proxy to end the session, but then you can't login.

**Additional context**
I could have this all wrong, so happy to be corrected.

**Comment by gtsteffaniak** [comment]
thanks! and yeah, good feature request, this functionality was added for [OIDC](https://github.com/gtsteffaniak/filebrowser/wiki/Configuration-And-Examples#openid-connect-configuration-oidc) as `logoutRedirectUrl`

I could add something similar for proxy auth.

**Comment by christaikobo** [comment]
Is this the same request as https://github.com/gtsteffaniak/filebrowser/issues/471?

Just tried 0.7.6 beta, doesn't seem to work.

Config
```
auth:
  tokenExpirationHours: 1
  methods:
    proxy:
      enabled: true
      header: "Remote-User"
      createUser: false
      logoutRedirectUrl: https://mydoamin.com/auth/logout
    password:
      enabled: false
      minLength: 16
    noauth: false
```
The logout URL is still `https://mydomain.com/filebrowser/api/auth/logout`

![Image](https://github.com/user-attachments/assets/bccc2985-121d-4694-a135-bf486f9c4770)
