### ISSUE TITLE
Onlyoffice integration stopped working in 0.7.5

### ISSUE THREAD

**Issue by auer1329** [gtsteffaniak/filebrowser#686]
**Description**
Onlyoffice integration is not working after upgrading from 0.7.4 to 0.7.5. After downgrade it works again.

The 0.7.5 release note mention some Onlyoffice configuration script, but it is not really clear to me what it does and if I need to change some config.

**Expected behaviour**
Opening Onlyoffice to edit the .xlsx file

**What is happening instead?**
Opening a .xlsx file shows "Loading..." indefinitely.

Onlyoffice logs:
```
Generating WOPI private key...Done
Generating WOPI public key...Done
 * Starting PostgreSQL 16 database server
   ...done.
 * Starting RabbitMQ Messaging Server rabbitmq-server
   ...done.
Connection to localhost (::1) 5432 port [tcp/postgresql] succeeded!
Connection to localhost (::1) 5672 port [tcp/amqp] succeeded!
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:4: NOTICE:  table "doc_callbacks" does not exist, skipping
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:9: NOTICE:  function merge_db(pg_catalog.varchar,int2,int8,pg_catalog.timestamp,pg_catalog.varchar,int8,int8) does not exist, skipping
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:10: NOTICE:  function merge_db(pg_catalog.varchar,int2,int4,pg_catalog.timestamp,pg_catalog.varchar,int4,int4) does not exist, skipping
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:11: NOTICE:  function merge_db(pg_catalog.varchar,int2,int4,pg_catalog.timestamp,int4,int4,text,text) does not exist, skipping
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron
   ...done.
 * Starting nginx nginx
   ...done.
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
Generating js caches, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx
   ...done.
Installing plugins, please wait...Done
 * Reloading nginx configuration nginx
   ...done.
```

**Additional context**
Portainer compose file:
```
services:
  filebrowser:
    image: ghcr.io/gtsteffaniak/filebrowser:0.7.5-beta
    container_name: filebrowser-quantum
    volumes:
      - local:/local
      - db:/database
      - /docker/filebrowser-quantum/config.yml:/home/filebrowser/config.yaml
      - media:/volume1/media:ro
      - home:/volume1/home:ro
    restart: unless-stopped
    networks:
      - proxy_bridge
    
  onlyoffice:
    image: onlyoffice/documentserver:8.3.3
    container_name: filebrowser-onlyoffice
    environment:
      - JWT_SECRET=supersecurejwtsecret
    restart: unless-stopped
    networks:
      - proxy_bridge

volumes:
  local:
  db:
  media:
  home:

networks:
  proxy_bridge:
    external: true
```

**How to reproduce?**
Update docker image from 0.7.4 to 0.7.5
