### ISSUE TITLE
wiki: change the auth config example and minimal config example yaml

### ISSUE THREAD

**Issue by scratchmex** [gtsteffaniak/filebrowser#719]
on https://github.com/gtsteffaniak/filebrowser/wiki/Configuration-And-Examples

```yaml
auth:
  signup: false <<< this option
  methods:
    noauth: false
    password:
      enabled: true
      minLength: 7  # set min password length requirement -- defaults to 5 if unset
      --- should be here
```

also, this is the minimal config (that I used)

```yaml
server:
  sources:
    - path: "/srv/data"

auth:
  methods:
    noauth: true
```
