### ISSUE TITLE
Prevent Auto-Created OIDC Users from Having Default Folder Access

### ISSUE THREAD

**Issue by baur** [gtsteffaniak/filebrowser#743]
**Is your feature request related to a problem? Please describe.**

When using OIDC with the createUser: true option:

```
    oidc:
      enabled: true
      clientId: "filebrowser-client"
      clientSecret: "***"
      issuerUrl: http://localhost:4000
      scopes: "openid profile email"
      createUser: true
```

New users are automatically created upon first login and are immediately granted access to a folder by default, even though no explicit permissions have been set.

![Image](https://github.com/user-attachments/assets/03c6c65e-922e-4bda-84ed-21055a00e100)

**Describe the solution you'd like**

Automatically created users should not have access to any folders by default. Instead, access should be explicitly assigned by an admin after the user is created.

**Optional enhancement**

Maybe allow configuration of default permissions or folder access behavior for auto-created users.
