### ISSUE TITLE
Docker Not Starting

### ISSUE THREAD

**Issue by hxck** [gtsteffaniak/filebrowser#751]
Currently I have:

```
services:
  filebrowserquantum:
    volumes:
      - /:/srv
      - ./data:/home/filebrowser/data
    ports:
      - 8076:80
    environment:
      - FILEBROWSER_CONFIG=data/config.yaml
    image: gtstef/filebrowser
    restart: always
networks: {}
```

```
server:
  port: 8076                              # port to listen on
  database: "data/database.db"            # path to the database file
  sources:                                # validate:required,dive
    - path: /srv	                  # file system path. (Can be relative)  validate:required
      name: backend                       # display name
      config:
        ignoreHidden: false               # ignore hidden files and folders.
        ignoreZeroSizeFolders: false      # ignore folders with 0 size
auth:
  adminUsername: admin                    # the username of the admin user. If not set, the default is "admin".
  adminPassword: LT$*1DipY2#8csHsh%vb     # the password of the admin user. If not set, the default is "admin".
userDefaults:
  preview:
    image: true
  loginMethod: password                   # login method to use: eg. password, proxy, oidc
```

for compose and config. It seems like it spins up fine, but it gets stuck at indexing:

```
filebrowserquantum-1  | 2025/06/12 02:03:01 [INFO ] Initializing FileBrowser Quantum (v0.7.8-beta)
filebrowserquantum-1  | 2025/06/12 02:03:01 [INFO ] Using Config file        : data/config.yaml
filebrowserquantum-1  | 2025/06/12 02:03:01 [INFO ] Auth Methods             : [password]
filebrowserquantum-1  | 2025/06/12 02:03:01 [INFO ] Using existing database  : data/database.db
filebrowserquantum-1  | 2025/06/12 02:03:01 [INFO ] Sources                  : [backend: /srv]
filebrowserquantum-1  | 2025/06/12 02:03:02 [INFO ] Media Enabled            : true
filebrowserquantum-1  | 2025/06/12 02:03:02 [INFO ] Running at               : http://localhost:8076/
filebrowserquantum-1  | 2025/06/12 02:03:02 [INFO ] initializing index: [backend]
```

I've let it go for a long time and it doesn't seem to get past this spot. I'm currently running the base Filebrowser with the same volume ```/:/srv``` but even with deleting that stack it still doesn't spin up completely.

Any ideas? Thanks!

**Comment by gtsteffaniak** [comment]
if you enable debug logging what do you see? 

```
server:
  logging:
    - output: stdout
      levels: "info|warning|error|debug"
```
