### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by hxck** [gtsteffaniak/filebrowser#754]
Sorry to open another issue, but you closed the other one before I could respond and this is technically a different issue.

I decided to keep my old FB setup for that particular purpose, and added specific mounts for this one. It does spin up correctly in Docker and I see the indexing in the logs, but I still get a ```Connection Refused``` when accessing. Docker is running on a server and I access through my main PC via IP (192.168-) instead of ```localhost```. I didn't see anything in the Getting Started about setting a URL and the proxy stuff I saw was related to Auth, so I'm not sure how to proceed.

Thanks!

**Comment by gtsteffaniak** [comment]
"Connection refused" is very specific. It means the port you are trying to access is not open for listening (either wrong host + port combo , or your service is not listing on that host + port combo). 

are you exposing a port from docker when you run it, from the [getting started](https://github.com/gtsteffaniak/filebrowser/wiki/Getting-Started#without-docker):

```
docker run -u filebrowser -it -v $(pwd)/config.yaml:/home/filebrowser/config.yaml -v /path/to/folder:/srv -p 80:80 gtstef/filebrowser
```

Let me break down what the ports indicate here:

`80:80` means: `[docker external network port]:[filebrowser application port]`


so docker takes the internal port which is default: 80 for filebrowser and exposes it to your docker network over the port `80`

I would recommend keeping the internal docker filebrower port 80 (in your config file).

Then if you already have the old FB running at port 80 on docker, you will need to change the filebrowser quantum port to something other than 80, like 8080.

also see `docker ps` to confirm what containers are running on what ports.

**Comment by hxck** [comment]
Sorry, I didn't mean to make it sound like I'm new lol, I should've been more specific. I have over 50 containers running strong at the moment but I'm not getting much in the logging about my issue.

I did set port 8076 in my compose, and nothing else is running on that port. I can't use 80 since Traefik is using it, but I don't have Traefik set up for this container. Normally I can just drop in a compose and I'm good to go, but I'll get ```Connection Refused``` when it's something that needs a specific URL environment variable set. Like for example with Docmost I have to set ```"APP_URL: http://IP"``` or it doesn't resolve correctly. I know it's common with stuff for NextJS if it isn't baked into the container, I'm not really sure what the situation is here.

I have logging turned on and I don't see anything except
```filebrowserquantum-1  | 2025/06/13 01:26:54 [INFO ] httpRouter.go:191: Running at: http://localhost:8076/```
In most cases I would just need a way to set it to 0.0.0.0 or 192.168.50.200 etc. I didn't really see anything in docs related to this so apologies if I'm missing something.

Thanks.

**Comment by gtsteffaniak** [comment]
Could you show your docker compose?

**Comment by hxck** [comment]
```
services:
  filebrowserquantum:
    volumes:
      - /opt/stacks:/stacks
      - /mnt/film:/film
      - /mnt/tv:/tv
      - /mnt/storage/music:/music
      - ./data:/home/filebrowser/data
    ports:
      - 8076:80
    environment:
      - FILEBROWSER_CONFIG=data/config.yaml
    image: gtstef/filebrowser
    restart: always
networks: {}
```
