### ISSUE TITLE
[Bug] No File Operations Shown In Popup Menu

### ISSUE THREAD

**Issue by royaltongue** [gtsteffaniak/filebrowser#775]
**Description**
When right clicking a file or folder, the only options shown are as follows:

![Image](https://github.com/user-attachments/assets/e7796171-9705-4fb1-a900-d0699e3d1af1)

**Expected behaviour**
I expect to see other options, such as copy, move, share, delete, etc

**What is happening instead?**
Only 3 options are shown

**Additional context**
Container is running as root. This happens with any file or folder, not just the one shown above

My `docker-compose.yml`:
```
filebrowser:
    container_name: filebrowser
    image: gtstef/filebrowser
    volumes:
      - ${dcs}/filebrowser/home/filebrowser/database:/home/filebrowser/database
      - ${dcs}/filebrowser/home/filebrowser/config.yaml:/home/filebrowser/config.yaml
      #################################
      - /srv:/srv
    hostname: filebrowser
    networks:
      - caddy_local
    restart: unless-stopped
```

My `config.yaml`:
```
server:
  port: 80
  database: "/home/filebrowser/database/database.db"
  sources:
    - path: "/srv"
      name: srv
auth:
  methods:
    password:
      enabled: false # set to false if you only want to allow OIDC
    oidc:
      enabled: true                              # whether to enable OIDC authentication
      clientId: "[redacted]"                            # client id of the OIDC application
      clientSecret: "[redacted]"                        # client secret of the OIDC application
      issuerUrl: "https://auth.[redacted].[redacted]/application/o/filebrowser/" # authorization URL of the OIDC provider
      scopes: "email openid profile"             # scopes to request from the OIDC provider
      userIdentifier: "username"     # the user identifier to use for authentication. Default is "username", can be "email" or "username", or "phone"
      disableVerifyTLS: false        # disable TLS verification for the OIDC provider. This is insecure and should only be used for testing.
      logoutRedirectUrl: ""          # if provider logout url is provided, filebrowser will also redirect to logout url. Custom logout query params are respected.
      createUser: true               # create user if it does not exist
      adminGroup: "Administrators" # if set, users in this group will be granted admin privileges.
```

**How to reproduce?**
Right click on any file or folder

**Files**
Github would not allow me to upload a `.ini` file, so I changed the extension to `.txt`

[sabnzbd.ini.txt](https://github.com/user-attachments/files/20739128/sabnzbd.ini.txt)
