### ISSUE TITLE
Disabled indexing for subfolders but allow browsing 

### ISSUE THREAD

**Issue by ktdd** [gtsteffaniak/filebrowser#783]
**Description**
Disabled indexing for a source in config.yaml and now I can't browse at all.

**Expected behaviour**
I expect to still see the files.

**What is happening instead?**
No files are shown. Debug log says:
indexingFiles.go:113: skipping directory / due to exclusion rules

**Additional context**
Version 0.7.9-beta, Ubuntu 24

I also tried without disabling indexing and instead added two folders to exclude > folders. I can now see every other folder than those two excluded ones and if I try to enter them manually I get an error: "could not refresh file info: directory or item excluded from indexing". Isn't this how exclude works?

**Comment by gtsteffaniak** [comment]
There were changes and I tested this as I made that change, but this is unexpected. Will take another look

**Comment by gtsteffaniak** [comment]
Re-tagged 0.7.9 with a fix, can you pull the new version and try again?

**Comment by ktdd** [comment]
### Source 1 (indexing disabled):

I can now browse every directory so that got fixed. Debug log still prints "skipping directory due to exclusion rules" every time I navigate to new directory. No biggie.

### Source 2 (excluded one huge subdirectory that doesn't need to be indexed):
I can see the excluded subdir in root view but when I try to enter it, I get a couple of errors and can't enter the directory.

Frontend: Error: {"status":500,"message":"could not refresh file info: directory or item excluded from indexing"}

Backend: [ERROR] middleware.go:419: GET     | 500 | 192.168.0.132:51817 | admin        | 0ms          | "/api/resources?path=%2F[excluded_directory]%2F&source=[source_name]

**Comment by gtsteffaniak** [comment]
I'm not sure what my goal is for exclusions or how I want to handle it.

At first it was just to ignore indexing to save memory and processing power.
 
But recently the goal was to hide it from the UI as well, so I would want it to be hidden.

Perhaps I should add an option in each exclude to allow viewing in ui still if desired, just not to index.

Maybe:

```
server:
  sources:
    - name: "mysource"
      path: "/mnt/folder"
      config:
        exclude:
          allowBrowsing: true
          folders:
            - "/subfolder/ignoreMe"
```

**Comment by gtsteffaniak** [comment]
What behavior do you expect or what would you like?

**Comment by ktdd** [comment]
I'd definitely would like to disable indexing for some subdirectories but still allow browsing them. At first I thought that "neverWatchPaths" config setting would allow it, but I don't think the setting does anything.

How about this:
```
server:
  sources:
    - name: "mysource"
      path: "/mnt/folder"
      config:
        exclude:
          folders:
            - "/subfolder1"
              allowBrowsing: true
            - "/subfolder2"
              allowBrowsing: false
```

Or if neverWatchPaths can be utilized, could we use it to disable indexing and use exclude for completely hiding directories?
