### ISSUE TITLE
user setting not persisting after container is redeployed.

### ISSUE THREAD

**Issue by tinkermesomething** [gtsteffaniak/filebrowser#814]
**Description**
User settings/preferences are lost when the container is deleted and redeployed. 

**Expected behaviour**
User settings/preferences should persist when a container is deleted and redeployed.

**What is happening instead?**
User settings/preferences are lost when the container is deleted and redeployed. 

**How to reproduce?**
Set shares and colours for a OIDC user and when the container is deleted and recreated,  the user settings and preferences will be gone.

**Comment by gtsteffaniak** [comment]
Thanks for opening this, I will test this. Just to confirm, you have a persistent database and redeploying keeps users? Just certain settings are missing?

And I am sure not all of these settings, which settings and preferences get reset?

**Comment by tinkermesomething** [comment]
I do indeed have persistent DB and config mounted locally to /opt/filebrowser/DB etc. 
not sure about other users as I only experienced this with my OIDC user.

**Comment by gtsteffaniak** [comment]
Ah right! That's actually a great clue because the user now gets updated every time it logs in.

I'll test an oidc user with this and confirm.

**Comment by gtsteffaniak** [comment]
I can't replicate this even for oidc users. Are you sure you have a persistent database?

Since OIDC could automatically create a user, you might not realize that you don't have a persistent database.

When you startup the application do you see a message indicating its using the same database?

```
[INFO ] Using existing database  : database.db
```

**Comment by tinkermesomething** [comment]
ah!
from the logs, it appears it creates a new DB each time:

```
2025/06/21 19:14:21 [INFO ] OIDC Auth configured successfully

2025/06/21 19:14:21 [INFO ] Initializing FileBrowser Quantum (v0.7.9-beta)

2025/06/21 19:14:21 [INFO ] Using Config file        : /home/filebrowser/config.yaml

2025/06/21 19:14:21 [INFO ] Auth Methods             : [oidc]

2025/06/21 19:14:21 [INFO ] Creating new database    : /home/filebrowser/data/database.db
```

is there something in config.yaml that should instruct not to create a new DB each time?

**Comment by gtsteffaniak** [comment]
that means it couldn't find the database file:

```
/home/filebrowser/data/database.db
```

Are you mounting that properly? Using docker? I have cleaned up the [getting started](https://github.com/gtsteffaniak/filebrowser/wiki/Getting-Started#docker-compose) recently, does your configuration match?

**Comment by tinkermesomething** [comment]
yeah I reckon that's where I went wrong.

this is my current docker compose:

```yaml
services:
  filebrowser:
    image: gtstef/filebrowser
    environment:
      FILEBROWSER_CONFIG: "/home/filebrowser/config.yaml"
    volumes:
      - /media/MVIES:/folder/movies
      - /media/SHWS:/folder/shows
      - /opt/filebrowser/db/database.db:/home/filebrowser/database.db
      - /opt/filebrowser/config.yaml:/home/filebrowser/config.yaml
    ports:
      - "5580:80"
    restart: always
```

As you can see, I had placed the DB in the wrong folder 😟
