### ISSUE TITLE
Allow no default sources for new users

### ISSUE THREAD

**Issue by RikiTheHeropon** [gtsteffaniak/filebrowser#834]
**Description**
I am attempting to limit allowed sources and scopes for specific users.

**Expected behaviour**
For defined allowed sources and user scope to be persistent after restarting the container.

**What is happening instead?**
Works as intended until restarting the container, in which case all users have access to default paths of all sources defined in config.yaml again.

**Additional context**
The additional user does not have admin privileges if that affects anything. I also verified that my database is persistent, as logs show the "using existing database" message on startup while keeping all other user info.

**How to reproduce?**
Creating another user and customizing their allowed sources to differ from the default in config.yaml, then saving changes and restarting the container; this resets the allowed sources customization.

**Comment by Darkassassin07** [comment]
Do you have a persistent db? (container path: /home/filebrowser/data/database.db)

Are you perhaps using OIDC with create user enabled, and the users are being re-created on login? 

Gave this a test with password auth, and user sources+scopes are being retained throughout restarts for me.

**Comment by gtsteffaniak** [comment]
@Darkassassin07's suggesting is something to confirm.

If you have a persistent database, this is unexpected. Make sure your logs say its "using existing database" when it starts. Can you provide your config?

Some relevant config properties are the [default source configurations](https://github.com/gtsteffaniak/filebrowser/wiki/Configuration-And-Examples#default-source-configuration) described here.

**Comment by RikiTheHeropon** [comment]
Thanks for the reply!

Just double-checked and logs still provide the line "2025/06/25 01:37:49 [INFO ] Using existing database  : /home/filebrowser/data/database.db" on each restart as previously mentioned.

I did manage to narrow it down though; only the first source that is defined under the sources list in config.yaml will always be the one to reappear. The first source happens to be the only one I excluded from other users, originally leading me to believe this happened with all sources. As an example, here's my config:

```
server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/storage/downloads"
      name: "Downloads"
      config:
	defaultUserScope: "/"
        defaultEnabled: false
    - path: "/storage/documents"
      name: "Documents"
      config:
	defaultUserScope: "/"
        defaultEnabled: false
    - path: "/storage/photos"
      name: "Photos"
      config:
	defaultUserScope: "/"
        defaultEnabled: false
    - path: "/storage/videos"
      name: "Videos"
      config:
	defaultUserScope: "/"
        defaultEnabled: false
userDefaults:
  preview:
    image: true
    popup: true
    video: true
    office: false
    highQuality: false
  darkMode: true
  disableSettings: false
  singleClick: true
  permissions:
    admin: false
    modify: false
    share: false
    api: false
```

The downloads source was the one that kept reappearing as an allowed source for all users after restart. For testing, I removed that source from my config and created a fresh persistent database with a test user for good measure; that test user was configured to only be allowed access to the videos source. After a container restart, documents access appears on its own but _not_ the photos source.

Sorry in advance, I realize this is a really specific issue (and it's probably of my own doing with my luck). I can work around it for now by changing the order of my sources in config.yaml.

Thanks for creating this fork of FileBrowser, I've really been enjoying using it so far!
