### ISSUE TITLE
adminUsername/Password not recognized

### ISSUE THREAD

**Issue by Prophet-Phoenix** [gtsteffaniak/filebrowser#843]
**Description**
I set the adminUsername and adminPassword values in my config.yaml, still the admin user/pw is admin/admin. 

**Expected behaviour**
Should be the values i wrote in config.yaml or give an error, that it couldn't parse some of the lines there.

**What is happening instead?**
No error messages in log.

**Additional context**
I probably messed up because i'm not used to writing yaml. Still, in that case, i should be warned about the incorrect values.

**How to reproduce?**
Run latest beta with docker with -c my/config.yaml

```
server:
  baseURL: /
  cacheDir: /home/filebrowser/data/cache
  sources:
    - path: "/srv"
      name: unRaid
auth:
  adminUsername: "email@example.com"
  adminPassword: "soMe.#CharaCters:l(&TZ"
frontend:
  name: My Cloud
```
(Didn't work without " either.)
