### ISSUE TITLE
Errors on startup attempting to find data directory

### ISSUE THREAD

**Issue by varadins** [gtsteffaniak/filebrowser#845]
**Description**
I am spinning this up with a docker-compose.yml file and have set my volumes and config file.  I am receiving an error that it is unable to find the folder I specified.

**Expected behaviour**
Server should start after finding the directories I have specified.

**What is happening instead?**
```
**2025/06/24 20:39:09 [FATAL] configured source path does not exist: /home/docker/docker/quantum/jellyfin**
```

**Additional context**
The folder exists: 

```
docker@docker1:~/docker/quantum/data$ cd /home/docker/docker/quantum/jellyfin
docker@docker1:~/docker/quantum/jellyfin$ pwd
/home/docker/docker/quantum/jellyfin
```

**Files**

docker-compose.yml
```
  filebrowser:
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: REDACTED
    volumes:
      - '/home/docker/docker/quantum' # Never mount root "/" directory to docker, always choose a sub-folder with your data.
      - '/home/docker/docker/quantum/data:/home/filebrowser/data' # mount the data folder you created with the config file.
      # Advanced: If you plan to run with a different user besides root or filebrowser, you will need to mount a tmp directory.
      # - './tmp/:/home/filebrowser/tmp/'
    ports:
      - '10000:80' # the left 80 is the port **you will use** to access. The right 80 is the container port that **must match the config.yaml**
    image: gtstef/filebrowser
    # Optionally run as non-root filebrowser user
    #user: filebrowser
    restart: unless-stopped
```
data/config.yaml

```
server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/home/docker/docker/quantum/jellyfin"
userDefaults:
  preview:
    image: true
    popup: true
    video: false
    office: false
    highQuality: false
  darkMode: true
  disableSettings: false
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
```
