### ISSUE TITLE
Unable to start Quantum Filebrowser

### ISSUE THREAD

**Issue by wilcochris** [gtsteffaniak/filebrowser#847]
**Description**
Unable to spin up Docker container

**Expected behaviour**
Quantum to be up and running

**What is happening instead?**
[FATAL] config file /srv/configs/quantum/data/config.yml does not exist, please create it or set the FILEBROWSER_CONFIG environment variable to a valid config file path

**Additional context**
config.yml is present in the location specified in the docker-compose file

**How to reproduce?**
I'm not sure if it can be reproduced on another setup

**Files**

[config.txt](https://github.com/user-attachments/files/20901773/config.txt)
[docker-compose.txt](https://github.com/user-attachments/files/20901774/docker-compose.txt)

**Comment by wilcochris** [comment]
Logs now show the following error

```
2025/06/25 12:23:14 [FATAL] configured source path does not exist: /srv/configs/quantum/chris
```

The path is there

```
chris@DOCK01:/srv/configs/quantum$ cd chris/
chris@DOCK01:/srv/configs/quantum/chris$ pwd
/srv/configs/quantum/chris
```

docker-compose.yml
```
services:
  filebrowser:
    environment:
      FILEBROWSER_CONFIG: "data/config.yml"
      FILEBROWSER_ADMIN_PASSWORD: admin
    volumes:
      - '/srv/configs/quantum/chris:/folder' # Never mount root "/" directory to docker, always choose a sub-folder with your data.
      - '/srv/configs/quantum/data/filebrowser.db:/home/filebrowser/database'
      - '/srv/configs/quantum/data/config.yml:/home/filebrowser/config.yml' # mount the data folder you created with the config file.
      - '/srv/configs/quantum/data:/home/filebrowser/data'
      # Advanced: If you plan to run with a different user besides root or filebrowser, you will need to mount a tmp directory.
      # - './tmp/:/home/filebrowser/tmp/'
    ports:
      - '7777:80' # the left 80 is the port **you will use** to access. The right 80 is the container port that **must match the config.yaml**
    image: gtstef/filebrowser
    # Optionally run as non-root filebrowser user
    user: filebrowser
    restart: unless-stopped
    container_name: quantum
```
config.yml

```
server:
  port: 7777
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/srv/configs/quantum/chris/"
  database: "/srv/configs/quantum/data/filebrowser.db"
userDefaults:
  preview:
    image: true
    popup: true
    video: false
    office: false
    highQuality: false
  darkMode: true
  disableSettings: false
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
auth:
  adminUsername: admin
  adminPassword: admin
```

**Comment by Darkassassin07** [comment]
In your first compose file, you're mounting your config to: /home/filebrowser/config.yml but telling filebrowser to look for it at /home/filebrowser/data/config.yml


`volumes:`
`-'./data/config.yml:/home/filebrowser/config.yml'`
`environment:`
`FILEBROWSER_CONFIG: "./data/config.yml
`


Then, in the second compose; you've added the correct mount for the config folder, but you've mounted your source location to the folder '/folder', but told filebrowser about the host location '/srv/configs/quantum/chris' instead:

`volumes:`
`- '/srv/configs/quantum/chris:/folder'`


Looks like you just keep swapping host/container paths. Left of the colon is the path on the host, right of the colon is the path it should map to in the container.

**Comment by wilcochris** [comment]
The second comment I added is pulled from the docs here.

They are so unclear. It’s not easy to set this up.

I’m not the only one that is getting the fatal error about the path.

You can see the path exists on my system

**Comment by Darkassassin07** [comment]
The path exists on the host system, but it does not exist within the container because you have not put the correct paths into your compose file and config.

Looking at the compose file in your second comment:

You have 4 volumes mounted.

The first one has your source folder mounted to the location '/folder' inside the container, but that is not the path you've given filebrowser in its config.yml. You gave filebrowser the path on the host instead of giving it the path inside the container ('/folder').

The next two are wrong and not being used by filebrowser at all.

The fourth one correctly mounts your config and database by mounting the data folder on the host to the correct location in the container.

```
services:
  filebrowser:
    environment:
      FILEBROWSER_CONFIG: "data/config.yml"
      FILEBROWSER_ADMIN_PASSWORD: admin
    volumes:
      - '/srv/configs/quantum/chris:/folder'   #left of colon=host. right of colon=container
      - '/srv/configs/quantum/data:/home/filebrowser/data'
    ports:
      - '7777:80' # the left 7777 is the port **you will use** to access. The right 80 is the container port that **must match the config.yaml**
    image: gtstef/filebrowser
    # Optionally run as non-root filebrowser user
    user: filebrowser
    restart: unless-stopped
    container_name: quantum
```

You are configuring a service that runs in a container, stop changing all the config paths to paths outside the container.

```
server:
  port: 80 #NOT 7777, as the compose says, this MUST match the compose
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/folder" #path files were mounted to in docker compose volumes, NOT THE PATH ON THE HOST
  database: "/home/filebrowser/data/filebrowser.db" #again CONTAINER paths, NOT HOST PATHS
userDefaults:
  preview:
    image: true
    popup: true
    video: false
    office: false
    highQuality: false
  darkMode: true
  disableSettings: false
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
auth:
  adminUsername: admin
  adminPassword: admin 
```

**Comment by molnarti** [comment]
i am also very confused by this. i am running more than 50 containers in my homelab, but for some reason i am failing to set this up properly. the documentation using confusing naming also does not help, like using a directory called `data` for configurations. 

this is my compose file:
```
networks:
  default:
      name: $DEF_NETWORK
      external: true

services:
  filebrowser:
    container_name: filebrowser-quantum
    environment:
      - FILEBROWSER_CONFIG="data/config.yaml"
#      - PUID=$PUID
#      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - '/StoragePool:/Storage' # Never mount root "/" directory to docker, always choose a sub-folder with your data.
      - './config:/home/filebrowser/data' # mount the data folder you created with the config file.
      # Advanced: If you plan to run with a different user besides root or filebrowser, you will need to mount a tmp di>      - './tmp/:/home/filebrowser/tmp/'
    ports:
      - '8881:80' # the left 80 is the port **you will use** to access. The right 80 is the container port that **must >    image: gtstef/filebrowser
    # Optionally run as non-root filebrowser user
    user: filebrowser
    restart: unless-stopped
```

when starting it like this i am getting a FATAL error about `data/config.yaml` not existing. when i remove the FILEBROWSER_CONFIG variable from my compose and run the container, then exec into it i can clearly see the config.yaml mounted in the `/home/filebrowser/data` directory
```
 $ ls -la data
total 14
drwxrwsrwx    2 filebrowser users            4 Jun 25 22:34 .
drwxr-sr-x    1 filebrowser filebrowser         4 Jun 25 22:40 ..
-rw-rw-r--    1 filebrowser users         9979 Jun 25 00:09 config.yaml
-rw-------    1 filebrowser users        65536 Jun 25 22:34 database.db
```
i have tried various changes, like adding the absolute path to the compose file, e.g.  `FILEBROWSER_CONFIG="/home/filebrowser/data/config.yaml"` but the container still cannot find it. 

it would be much easier if the app created the config file after the first run and you could edit it, even from the app itself.
