### ISSUE TITLE
some API endpoints always return 404

### ISSUE THREAD

**Issue by hss-wodom** [gtsteffaniak/filebrowser#849]
**Description**
I have a new but seemingly fully functional install using docker compose with caddy as a reverse proxy. Interacting via the UI has been smooth, but whether it's due to a config issue on my end or an actual issue, I'm getting 404s from some (but not all) API endpoints, even just trying to make test calls via the Swagger UI. I haven't tested every endpoint yet, but so far my results are:

Working:
- `/health`
- `/api/shares`
- `/api/settings`
- `/api/resources`

Returns 404:
- `/api/users/{id}`
- `/api/listApiKeys`

If anyone has any ideas about either what I may have misconfigured or of things I should try to help narrow it down please don't hesitate to share. I'm happy to provide as much info as would be helpful, but I'll start with just one complete example - getting info about a user via `/api/users/{id}`. 

**How to reproduce?**
1. Go to the user settings on the admin account to get the user ID; I can see that it has `id=1` via the URL (`https://filebrowser.example.com/settings/users/1#`).
2. If you don't have one already, create an API key with appropriate permissions. I gave this one everything for testing.
3. Go to the swagger UI to test the endpoint - `https://filebrowser.example.com/swagger/index.html#/Users/get_api_users__id_`.
4. Click "Try it out".
5. Type `1` in the User ID field.
6. Click "Execute".

**Expected behaviour**
The API returns information about my user.

**What is happening instead?**
The API returns "404 page not found".

**Additional context**
- It happens in Firefox and Chrome via Swagger as well as from Postman.
- I've tried creating other users and API keys via the UI, but the results are the same.
- When I create an API key the site behaves a little strangely:
    - when I click "Create" after setting the options nothing appears to happen.
    - If I click "Create" again then I get an error saying "Error 409: key already exists with same name `<name>` ".
    - Rather than clicking a 2nd time, if I instead just close the key creation modal after clicking "Create" once and then reload the page, I can see my key.
    - This seems like it could just be an issue with an unrelated callback function or something like that, but given that it's api-related I wanted to mention it.

**Files**
compose.yaml

```
services:
  filebrowser:
    container_name: filebrowser
    image: gtstef/filebrowser
    restart: unless-stopped
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
    volumes:
      - '/etc/filebrowser/files:/files'
      - '/etc/filebrowser/data:/home/filebrowser/data'
      - '/var/log/filebrowser.log:/var/log/filebrowser.log'
    ports:
      - '8080:80'
```

config.yaml
```
server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
    - apiLevels: "info|warning|error"
    - output: "/var/log/filebrowser.log"
  sources:
    - path: "/files/public"
      config:
        defaultEnabled: true
    - path: "/files/personal"
      config:
        defaultEnabled: true
        createUserDir: true
    - path: "/files/secret"
      config:
        defaultEnabled: false
auth:
  methods:
    password:
      enabled: true
      minLength: 8
      signup: false
  adminUsername: "admin"
  adminPassword: "REDACTED"
frontend:
  name: FileBrowser Quantum
  disableDefaultLinks: true
  disableUsedPercentage: false
userDefaults:
  quickDownload: true
  preview:
    image: true
    popup: true
    video: true
    office: true
    highQuality: true
    motionVideoPreview: true
    disableHideSidebar: true
  darkMode: true
  disableSettings: false
  singleClick: true
  permissions:
    admin: false
    modify: false
    share: false
    api: false
```

Caddyfile
```
filebrowser.example.com {
    tls /etc/caddy/cert/fullchain.pem /etc/caddy/cert/privkey.pem
    encode zstd gzip
    reverse_proxy localhost:8080
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
    }
}
```
