### ISSUE TITLE
Users given access to additional sources on container restart.

### ISSUE THREAD

**Issue by Darkassassin07** [gtsteffaniak/filebrowser#867]
Here is my config:

````

server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/home/darkassassin07"
      name: "Darkassassin07"
      config:
        exclude:
          folders:
            - .cache/borg
            - .config/borg
    - path: "/mnt/Drobo"
      config:
        exclude:
          folders:
            - found.000
    - path: "/mnt/Backups"
      config:
        exclude:
          folders:
            - borg
  externalUrl: -redacted-
userDefaults:
  preview:
    image: true
    popup: true
    video: false
    office: false
    highQuality: false
  darkMode: true
  viewMode: list
  disableSettings: false
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
auth:
  adminUsername: -redacted-
  adminPassword: -redacted-
  tokenExpirationHours: 9

````

The first source has a 'name:' variable set, and I have a user that only has access to the first source, with a limited scope inside of it.

When that name variable is present, the restricted user is automatically granted access to the second source upon restarting the container.

If I comment out that name varable, this does not occur and the user remains restricted to the one source as configured.
